import { NextRequest, NextResponse } from 'next/server';
import { connectDB, DatabaseConnectionError } from '@/lib/db';
import Transaction from '@/models/Transaction';
import { getAuthPayload } from '@/lib/apiAuth';
import { logActivity } from '@/lib/activityLogger';

export async function GET(request: NextRequest) {
  try {
    await connectDB();
    const user = await getAuthPayload(request);
    if (!user) {
      return NextResponse.json({ error: 'Unauthorized' }, { status: 401 });
    }

    if (!user.normalizedRoles.some(r => ['Admin', 'Accountant', 'Finance Manager'].includes(r))) {
      return NextResponse.json({ error: 'Forbidden' }, { status: 403 });
    }

    const { searchParams } = new URL(request.url);
    const page = parseInt(searchParams.get('page') || '1');
    const limit = parseInt(searchParams.get('limit') || '30');
    const type = searchParams.get('type') || '';
    const category = searchParams.get('category') || '';
    const startDate = searchParams.get('startDate');
    const endDate = searchParams.get('endDate');

    const query: Record<string, unknown> = {
      isDeleted: { $ne: true },
    };

    if (type) query.type = type;
    if (category) query.category = category;
    if ((startDate && startDate !== 'undefined' && startDate !== 'null') || (endDate && endDate !== 'undefined' && endDate !== 'null')) {
      query.date = {};
      if (startDate && startDate !== 'undefined' && startDate !== 'null') {
        const start = new Date(startDate);
        if (!isNaN(start.getTime())) {
          (query.date as Record<string, Date>).$gte = start;
        }
      }
      if (endDate && endDate !== 'undefined' && endDate !== 'null') {
        const end = new Date(endDate);
        if (!isNaN(end.getTime())) {
          end.setHours(23, 59, 59, 999);
          (query.date as Record<string, Date>).$lte = end;
        }
      }
      // If query.date was added but both were invalid, remove it
      if (Object.keys(query.date as object).length === 0) {
        delete query.date;
      }
    }

    const skip = (page - 1) * limit;

    const now = new Date();
    const startOfMonth = new Date(now.getFullYear(), now.getMonth(), 1);
    const endOfMonth = new Date(now.getFullYear(), now.getMonth() + 1, 0, 23, 59, 59, 999);

    const [transactions, total, stats, monthlyStats] = await Promise.all([
      Transaction.find(query).sort({ date: -1 }).skip(skip).limit(limit).lean(),
      Transaction.countDocuments(query),
      Transaction.aggregate([
        { $match: query },
        { $group: { _id: '$type', total: { $sum: '$amount' } } },
      ]),
      Transaction.aggregate([
        { 
          $match: { 
            isDeleted: { $ne: true }, 
            date: { $gte: startOfMonth, $lte: endOfMonth } 
          } 
        },
        { $group: { _id: '$type', total: { $sum: '$amount' } } },
      ]),
    ]);

    const income = stats.find(s => s._id === 'Income')?.total || 0;
    const expense = stats.find(s => s._id === 'Expense')?.total || 0;

    const thisMonthIncome = monthlyStats.find(s => s._id === 'Income')?.total || 0;
    const thisMonthExpense = monthlyStats.find(s => s._id === 'Expense')?.total || 0;
    const thisMonthProfit = thisMonthIncome - thisMonthExpense;

    return NextResponse.json({
      transactions,
      pagination: { page, limit, total, pages: Math.ceil(total / limit) },
      summary: { 
        income, 
        expense, 
        totalProfit: income - expense,
        thisMonthIncome,
        thisMonthExpense,
        thisMonthProfit
      },
    });
  } catch (error) {
    console.error('Get transactions error:', error);
    if (error instanceof DatabaseConnectionError) {
      return NextResponse.json({ error: error.message }, { status: error.statusCode });
    }
    return NextResponse.json({ error: 'Internal server error' }, { status: 500 });
  }
}

export async function POST(request: NextRequest) {
  try {
    await connectDB();
    const user = await getAuthPayload(request);
    if (!user) {
      return NextResponse.json({ error: 'Unauthorized' }, { status: 401 });
    }

    if (!user.normalizedRoles.some(r => ['Admin', 'Accountant', 'Finance Manager'].includes(r))) {
      return NextResponse.json({ error: 'Forbidden' }, { status: 403 });
    }

    const body = await request.json();
    const { date, type, category, amount, description, referenceId, referenceType } = body;

    if (!date || !type || !category || !amount || !description) {
      return NextResponse.json({ error: 'Required fields missing' }, { status: 400 });
    }

    const transaction = await Transaction.create({
      date: new Date(date),
      type,
      category,
      amount,
      description,
      referenceId,
      referenceType,
      isAutoGenerated: false,
      createdBy: user.userId,
    });

    await logActivity({
      userId: user.userId,
      userName: user.name,
      action: `Recorded ${type.toLowerCase()}: $${amount} - ${description}`,
      module: 'Finance',
      targetId: transaction._id.toString(),
      ipAddress: request.headers.get('x-forwarded-for') || 'unknown',
    });

    return NextResponse.json({ transaction }, { status: 201 });
  } catch (error) {
    console.error('Create transaction error:', error);
    if (error instanceof DatabaseConnectionError) {
      return NextResponse.json({ error: error.message }, { status: error.statusCode });
    }
    return NextResponse.json({ error: 'Internal server error' }, { status: 500 });
  }
}
