import { NextRequest, NextResponse } from 'next/server';
import { connectDB, DatabaseConnectionError } from '@/lib/db';
import CashSale from '@/models/CashSale';
import Car from '@/models/Car';
import Customer from '@/models/Customer';
import Transaction from '@/models/Transaction';
import { getAuthPayload } from '@/lib/apiAuth';
import { logActivity } from '@/lib/activityLogger';
import { generateInvoice } from '@/lib/invoiceGenerator';
import { processZatcaInvoice, calculateVat, ZATCA_VAT_RATE } from '@/lib/zatca/invoiceService';
import mongoose from 'mongoose';

export async function GET(
  request: NextRequest,
  { params }: { params: Promise<{ id: string }> }
) {
  try {
    const { id } = await params;
    const user = await getAuthPayload(request);
    if (!user) {
      return NextResponse.json({ error: 'Unauthorized' }, { status: 401 });
    }

    if (!['Admin', 'Sales Person'].includes(user.normalizedRole || '')) {
      return NextResponse.json({ error: 'Forbidden' }, { status: 403 });
    }

    await connectDB();

    const sale = await CashSale.findById(id).lean();
    if (!sale) {
      return NextResponse.json({ error: 'Sale not found' }, { status: 404 });
    }

    return NextResponse.json({ sale });
  } catch (error) {
    console.error('Get cash sale error:', error);

    if (error instanceof DatabaseConnectionError) {
      return NextResponse.json({ error: error.message }, { status: error.statusCode });
    }

    return NextResponse.json({ error: 'Internal server error' }, { status: 500 });
  }
}

export async function PUT(
  request: NextRequest,
  { params }: { params: Promise<{ id: string }> }
) {
  try {
    const { id } = await params;
    const user = await getAuthPayload(request);
    if (!user) {
      return NextResponse.json({ error: 'Unauthorized' }, { status: 401 });
    }

    if (!['Admin', 'Sales Person'].includes(user.normalizedRole || '')) {
      return NextResponse.json({ error: 'Forbidden' }, { status: 403 });
    }

    await connectDB();

    if (!mongoose.Types.ObjectId.isValid(id)) {
      return NextResponse.json({ error: 'Invalid sale ID' }, { status: 400 });
    }

    const sale = await CashSale.findById(id);
    if (!sale) {
      return NextResponse.json({ error: 'Sale not found' }, { status: 404 });
    }

    const currentStatus = (sale.status as string) || 'Active';
    if (currentStatus === 'Cancelled') {
      return NextResponse.json({ error: 'Cannot update cancelled sale' }, { status: 400 });
    }

    const body = await request.json();
    const { saleDate, salePrice, discountType, discountValue, agentName, agentCommission, notes, status, invoiceType, buyerTrn } = body;

    if (status !== undefined && status === 'Cancelled') {
      const currentStatus = (sale.status as string) || 'Active';
      if (currentStatus === 'Cancelled') {
        return NextResponse.json({ error: 'Sale already cancelled' }, { status: 400 });
      }

      const updatedSale = await CashSale.findByIdAndUpdate(
        id,
        { status: 'Cancelled' },
        { new: true }
      );

      // Update car back to available
      await Car.findByIdAndUpdate(sale.car, { status: 'In Stock' });

      // Soft delete related transaction
      await Transaction.findOneAndUpdate(
        { referenceId: sale._id.toString(), referenceType: 'CashSale', isAutoGenerated: true },
        { isDeleted: true }
      );

      await logActivity({
        userId: user.userId,
        userName: user.name,
        action: `Cancelled cash sale: ${sale.saleId}`,
        module: 'Sales',
        targetId: sale._id.toString(),
        ipAddress: request.headers.get('x-forwarded-for') || 'unknown',
      });

      return NextResponse.json({ sale: updatedSale });
    }

    if (salePrice !== undefined) {
      sale.salePrice = salePrice;
    }
    if (discountType !== undefined || discountValue !== undefined) {
      const effectiveDiscountType = discountType ?? sale.discountType ?? 'flat';
      const effectiveDiscountValue = discountValue !== undefined ? discountValue : (sale.discountValue ?? 0);
      const effectiveSalePrice = salePrice !== undefined ? salePrice : sale.salePrice;
      const computedDiscountAmount = effectiveDiscountType === 'percentage'
        ? Math.round(effectiveSalePrice * effectiveDiscountValue / 100 * 100) / 100
        : effectiveDiscountValue;
      sale.discountType = effectiveDiscountType;
      sale.discountValue = effectiveDiscountValue;
      sale.discountAmount = computedDiscountAmount;
    } else if (salePrice !== undefined) {
      // Re-apply existing discount against updated price
      if ((sale.discountType ?? 'flat') === 'percentage') {
        sale.discountAmount = Math.round(salePrice * (sale.discountValue ?? 0) / 100 * 100) / 100;
      }
    }
    sale.finalPrice = sale.salePrice - sale.discountAmount;
    if (agentName !== undefined) sale.agentName = agentName;
    if (agentCommission !== undefined) sale.agentCommission = agentCommission;
    if (notes !== undefined) sale.notes = notes;
    if (saleDate !== undefined) sale.saleDate = new Date(saleDate);

    const zatcaFieldChanged = invoiceType !== undefined || buyerTrn !== undefined;
    if (invoiceType !== undefined) sale.invoiceType = invoiceType;
    if (buyerTrn !== undefined) (sale as any).buyerTrn = buyerTrn;

    await sale.save();

    // Update transaction if exists
    await Transaction.findOneAndUpdate(
      { referenceId: sale._id.toString(), referenceType: 'CashSale', isAutoGenerated: true },
      { 
        amount: sale.finalPrice,
        description: `Cash sale ${sale.saleId} - Car ${sale.carId}`
      }
    );

    // Re-run ZATCA if invoiceType or buyerTrn changed
    if (zatcaFieldChanged) {
      try {
        const customerDoc = await Customer.findById(sale.customer).lean();
        const carDoc = await Car.findById(sale.car).lean();
        const vatInfo = calculateVat(sale.finalPrice, ZATCA_VAT_RATE);
        const zatcaResult = await processZatcaInvoice({
          referenceId: sale._id.toString(),
          referenceType: 'CashSale',
          saleId: sale.saleId,
          invoiceType: (sale.invoiceType as 'Standard' | 'Simplified') || 'Simplified',
          issueDate: new Date(sale.saleDate),
          supplyDate: new Date(sale.saleDate),
          buyer: {
            name: sale.customerName,
            trn: (sale as any).buyerTrn || '',
            buildingNumber: (customerDoc as any)?.buildingNumber,
            streetName: (customerDoc as any)?.streetName,
            district: (customerDoc as any)?.district,
            city: (customerDoc as any)?.city,
            postalCode: (customerDoc as any)?.postalCode,
            countryCode: (customerDoc as any)?.countryCode || 'SA',
            otherId: (customerDoc as any)?.otherId ? {
              id: (customerDoc as any).otherId,
              type: (customerDoc as any).otherIdType || 'CRN'
            } : undefined
          },
          lineItems: [{
            name: carDoc ? `${carDoc.brand} ${carDoc.model} (${sale.carId})`.trim() : sale.carId,
            quantity: 1,
            unitPrice: vatInfo.subtotal,
            vatRate: ZATCA_VAT_RATE,
            vatAmount: vatInfo.vatAmount,
            totalAmount: vatInfo.totalWithVat,
          }],
          subtotal: vatInfo.subtotal,
          vatTotal: vatInfo.vatAmount,
          totalWithVat: vatInfo.totalWithVat,
          notes: sale.notes,
          createdBy: user.userId,
        });
        await CashSale.findByIdAndUpdate(sale._id, {
          zatcaUUID: zatcaResult.uuid,
          zatcaQRCode: zatcaResult.qrCode,
          zatcaHash: zatcaResult.xmlHash,
          zatcaStatus: zatcaResult.status,
          zatcaResponse: zatcaResult.zatcaResponse,
          vatAmount: vatInfo.vatAmount,
          finalPriceWithVat: vatInfo.totalWithVat,
        });
      } catch (zatcaError) {
        console.error('ZATCA reprocessing failed:', zatcaError);
      }
    }

    await logActivity({
      userId: user.userId,
      userName: user.name,
      action: `Updated cash sale: ${sale.saleId}`,
      module: 'Sales',
      targetId: sale._id.toString(),
      ipAddress: request.headers.get('x-forwarded-for') || 'unknown',
    });

    const updatedSale = await CashSale.findById(sale._id).lean();
    return NextResponse.json({ sale: updatedSale });
  } catch (error) {
    console.error('Update cash sale error:', error);

    if (error instanceof DatabaseConnectionError) {
      return NextResponse.json({ error: error.message }, { status: error.statusCode });
    }

    return NextResponse.json({ error: 'Internal server error' }, { status: 500 });
  }
}

export async function DELETE(
  request: NextRequest,
  { params }: { params: Promise<{ id: string }> }
) {
  try {
    const { id } = await params;
    const user = await getAuthPayload(request);
    if (!user) {
      return NextResponse.json({ error: 'Unauthorized' }, { status: 401 });
    }

    if (!['Admin', 'Sales Person'].includes(user.normalizedRole || '')) {
      return NextResponse.json({ error: 'Forbidden' }, { status: 403 });
    }

    await connectDB();

    if (!mongoose.Types.ObjectId.isValid(id)) {
      return NextResponse.json({ error: 'Invalid sale ID' }, { status: 400 });
    }

    const sale = await CashSale.findById(id);
    if (!sale) {
      return NextResponse.json({ error: 'Sale not found' }, { status: 404 });
    }

    if (sale.status === 'Cancelled') {
      return NextResponse.json({ error: 'Sale already cancelled' }, { status: 400 });
    }

    // Soft delete - mark as cancelled
    sale.status = 'Cancelled';
    await Promise.all([
      sale.save(),
      Car.findByIdAndUpdate(sale.car, { status: 'In Stock' }),
      Transaction.findOneAndUpdate(
        { referenceId: sale._id.toString(), referenceType: 'CashSale', isAutoGenerated: true },
        { isDeleted: true }
      ),
    ]);

    await logActivity({
      userId: user.userId,
      userName: user.name,
      action: `Cancelled cash sale: ${sale.saleId}`,
      module: 'Sales',
      targetId: sale._id.toString(),
      ipAddress: request.headers.get('x-forwarded-for') || 'unknown',
    });

    return NextResponse.json({ message: 'Sale cancelled successfully' });
  } catch (error) {
    console.error('Delete cash sale error:', error);

    if (error instanceof DatabaseConnectionError) {
      return NextResponse.json({ error: error.message }, { status: error.statusCode });
    }

    return NextResponse.json({ error: 'Internal server error' }, { status: 500 });
  }
}

export async function PATCH(
  request: NextRequest,
  { params }: { params: Promise<{ id: string }> }
) {
  try {
    const { id } = await params;
    const user = await getAuthPayload(request);
    if (!user) {
      return NextResponse.json({ error: 'Unauthorized' }, { status: 401 });
    }

    if (!['Admin', 'Sales Person'].includes(user.normalizedRole || '')) {
      return NextResponse.json({ error: 'Forbidden' }, { status: 403 });
    }

    await connectDB();

    if (!mongoose.Types.ObjectId.isValid(id)) {
      return NextResponse.json({ error: 'Invalid sale ID' }, { status: 400 });
    }

    const body = await request.json();
    const { action } = body;

    if (action === 'generate-invoice') {
      const sale = await CashSale.findById(id);
      if (!sale) {
        return NextResponse.json({ error: 'Sale not found' }, { status: 404 });
      }

      const [carData, customerData] = await Promise.all([
        Car.findById(sale.car).lean(),
        Customer.findById(sale.customer).lean(),
      ]);

      const invoiceUrl = await generateInvoice({
        saleId: sale.saleId,
        saleDate: sale.saleDate.toString(),
        carId: sale.carId,
        carBrand: carData?.brand,
        carModel: carData?.model,
        customerName: sale.customerName,
        customerPhone: sale.customerPhone,
        customerAddress: customerData?.address,
        salePrice: sale.salePrice,
        discountAmount: sale.discountAmount,
        finalPrice: sale.finalPrice,
        agentName: sale.agentName,
        agentCommission: sale.agentCommission,
      });

      sale.invoiceUrl = invoiceUrl;
      await sale.save();

      await logActivity({
        userId: user.userId,
        userName: user.name,
        action: `Regenerated invoice for cash sale: ${sale.saleId}`,
        module: 'Sales',
        targetId: sale._id.toString(),
        ipAddress: request.headers.get('x-forwarded-for') || 'unknown',
      });

      return NextResponse.json({ invoiceUrl, sale });
    }

    return NextResponse.json({ error: 'Invalid action' }, { status: 400 });
  } catch (error) {
    console.error('Patch cash sale error:', error);

    if (error instanceof DatabaseConnectionError) {
      return NextResponse.json({ error: error.message }, { status: error.statusCode });
    }

    return NextResponse.json({ error: 'Internal server error' }, { status: 500 });
  }
}
