import { NextRequest, NextResponse } from 'next/server';
import { connectDB, DatabaseConnectionError } from '@/lib/db';
import CashSale, { ICashSaleDocument } from '@/models/CashSale';
import EditRequest from '@/models/EditRequest';
import Car, { ICarRaw } from '@/models/Car';
import Customer, { ICustomerDocument } from '@/models/Customer';
import Transaction from '@/models/Transaction';
import { getAuthPayload } from '@/lib/apiAuth';
import { logActivity } from '@/lib/activityLogger';
import { generateInvoice } from '@/lib/invoiceGenerator';
import { processZatcaInvoice, calculateVat, ZATCA_VAT_RATE } from '@/lib/zatca/invoiceService';
import mongoose from 'mongoose';

export async function GET(
  request: NextRequest,
  { params }: { params: Promise<{ id: string }> }
) {
  try {
    const { id } = await params;
    const user = await getAuthPayload(request);
    if (!user) {
      return NextResponse.json({ error: 'Unauthorized' }, { status: 401 });
    }

    if (!user.normalizedRoles.some(r => ['Admin', 'Sales Person'].includes(r))) {
      return NextResponse.json({ error: 'Forbidden' }, { status: 403 });
    }

    await connectDB();

    const sale = await CashSale.findById(id).populate('car').lean();
    if (!sale) {
      return NextResponse.json({ error: 'Sale not found' }, { status: 404 });
    }

    return NextResponse.json({ sale });
  } catch (error) {
    console.error('Get cash sale error:', error);

    if (error instanceof DatabaseConnectionError) {
      return NextResponse.json({ error: error.message }, { status: error.statusCode });
    }

    return NextResponse.json({ error: 'Internal server error' }, { status: 500 });
  }
}

export async function PUT(
  request: NextRequest,
  { params }: { params: Promise<{ id: string }> }
) {
  try {
    const { id } = await params;
    const user = await getAuthPayload(request);
    if (!user) {
      return NextResponse.json({ error: 'Unauthorized' }, { status: 401 });
    }

    if (!user.normalizedRoles.some(r => ['Admin', 'Sales Person'].includes(r))) {
      return NextResponse.json({ error: 'Forbidden' }, { status: 403 });
    }

    await connectDB();

    if (!mongoose.Types.ObjectId.isValid(id)) {
      return NextResponse.json({ error: 'Invalid sale ID' }, { status: 400 });
    }

    const sale = await CashSale.findById(id);
    if (!sale) {
      return NextResponse.json({ error: 'Sale not found' }, { status: 404 });
    }

    const currentStatus = (sale.status as string) || 'Active';
    if (currentStatus === 'Cancelled') {
      return NextResponse.json({ error: 'Cannot update cancelled sale' }, { status: 400 });
    }

    const body = await request.json();
    const {
      saleDate,
      salePrice,
      discountType,
      discountValue,
      applyVat,
      vatRate,
      vatInclusive,
      agentName,
      agentCommission,
      agentCommissionType,
      agentCommissionValue,
      notes,
      status,
      invoiceType,
      buyerTrn,
    } = body;

    // INTERCEPTION: If not Admin, queue for approval
    if (!user.normalizedRoles.includes('Admin')) {
      await EditRequest.create({
        targetModel: 'CashSale',
        targetId: id,
        requestedBy: user.userId,
        proposedChanges: body,
        status: 'Pending'
      });

      await logActivity({
        userId: user.userId,
        userName: user.name,
        action: `Requested update for cash sale: ${id}`,
        module: 'Sales',
        targetId: id,
        ipAddress: request.headers.get('x-forwarded-for') || 'unknown',
      });

      return NextResponse.json({ 
        message: 'Edit request submitted for admin approval', 
        isPending: true 
      });
    }

    if (status !== undefined && status === 'Cancelled') {
      const currentStatus = (sale.status as string) || 'Active';
      if (currentStatus === 'Cancelled') {
        return NextResponse.json({ error: 'Sale already cancelled' }, { status: 400 });
      }

      const updatedSale = await CashSale.findByIdAndUpdate(
        id,
        { status: 'Cancelled' },
        { new: true }
      );

      // Update car back to available
      await Car.findByIdAndUpdate(sale.car, {
        status: 'In Stock',
        tafweedStatus: 'None',
        tafweedAuthorizedTo: '',
        tafweedDriverIqama: '',
        tafweedDurationMonths: null,
        tafweedExpiryDate: null,
      });

      // Soft delete related transaction
      await Transaction.findOneAndUpdate(
        { referenceId: sale._id.toString(), referenceType: 'CashSale', isAutoGenerated: true },
        { isDeleted: true }
      );

      await logActivity({
        userId: user.userId,
        userName: user.name,
        action: `Cancelled cash sale: ${sale.saleId}`,
        module: 'Sales',
        targetId: sale._id.toString(),
        ipAddress: request.headers.get('x-forwarded-for') || 'unknown',
      });

      return NextResponse.json({ sale: updatedSale });
    }

    if (salePrice !== undefined) {
      sale.salePrice = salePrice;
    }
    if (discountType !== undefined || discountValue !== undefined) {
      const effectiveDiscountType = discountType ?? sale.discountType ?? 'flat';
      const effectiveDiscountValue = discountValue !== undefined ? discountValue : (sale.discountValue ?? 0);
      const effectiveSalePrice = salePrice !== undefined ? salePrice : sale.salePrice;
      const computedDiscountAmount = effectiveDiscountType === 'percentage'
        ? Math.round(effectiveSalePrice * effectiveDiscountValue / 100 * 100) / 100
        : effectiveDiscountValue;
      sale.discountType = effectiveDiscountType;
      sale.discountValue = effectiveDiscountValue;
      sale.discountAmount = computedDiscountAmount;
    } else if (salePrice !== undefined) {
      // Re-apply existing discount against updated price
      if ((sale.discountType ?? 'flat') === 'percentage') {
        sale.discountAmount = Math.round(salePrice * (sale.discountValue ?? 0) / 100 * 100) / 100;
      }
    }
    sale.finalPrice = sale.salePrice - sale.discountAmount;
    const applyVatChanged = applyVat !== undefined;
    const vatRateChanged = vatRate !== undefined;
    const vatInclusiveChanged = vatInclusive !== undefined;

    if (applyVatChanged) {
      sale.applyVat = Boolean(applyVat);
    }

    const effectiveApplyVat = Boolean(sale.applyVat ?? ((sale.vatRate ?? 0) > 0));
    const requestedVatRate = vatRateChanged ? Number(vatRate) : Number(sale.vatRate);
    const effectiveVatRate = effectiveApplyVat ? (requestedVatRate || ZATCA_VAT_RATE) : 0;
    const effectiveVatInclusive = effectiveApplyVat ? (vatInclusiveChanged ? Boolean(vatInclusive) : Boolean(sale.vatInclusive)) : false;
    const vatInfo = calculateVat(sale.finalPrice, effectiveVatRate, effectiveVatInclusive);

    sale.vatRate = effectiveVatRate;
    sale.vatInclusive = effectiveVatInclusive;
    sale.vatAmount = vatInfo.vatAmount;
    sale.finalPriceWithVat = vatInfo.totalWithVat;

    if (agentName !== undefined) sale.agentName = agentName;
    if (agentCommission !== undefined) sale.agentCommission = agentCommission;
    if (agentCommissionType !== undefined) sale.agentCommissionType = agentCommissionType;
    if (agentCommissionValue !== undefined) sale.agentCommissionValue = agentCommissionValue;
    if (notes !== undefined) sale.notes = notes;
    if (saleDate !== undefined) sale.saleDate = new Date(saleDate);

    const zatcaFieldChanged = invoiceType !== undefined || buyerTrn !== undefined;
    if (invoiceType !== undefined) sale.invoiceType = invoiceType;
    if (buyerTrn !== undefined) sale.buyerTrn = buyerTrn;

    await sale.save();

    // Update transaction if exists
    await Transaction.findOneAndUpdate(
      { referenceId: sale._id.toString(), referenceType: 'CashSale', isAutoGenerated: true },
      { 
        amount: sale.finalPrice,
        description: `Cash sale ${sale.saleId} - Car ${sale.carId}`
      }
    );

    const shouldRerunZatca =
      zatcaFieldChanged ||
      salePrice !== undefined ||
      discountType !== undefined ||
      discountValue !== undefined ||
      applyVatChanged ||
      vatRateChanged ||
      vatInclusiveChanged;

    // Re-run ZATCA when invoice data changes
    if (shouldRerunZatca) {
      try {
        const customerDoc = sale.customer 
          ? await Customer.findById(sale.customer).lean() as unknown as ICustomerDocument 
          : null;
        const carDoc = await Car.findById(sale.car).lean() as unknown as ICarRaw;
        const zatcaResult = await processZatcaInvoice({
          referenceId: sale._id.toString(),
          referenceType: 'CashSale',
          saleId: sale.saleId,
          invoiceType: (sale.invoiceType as 'Standard' | 'Simplified') || 'Simplified',
          issueDate: new Date(sale.saleDate),
          supplyDate: new Date(sale.saleDate),
          buyer: {
            name: sale.customerName || 'Cash Customer',
            trn: sale.buyerTrn || '',
            buildingNumber: customerDoc?.buildingNumber,
            streetName: customerDoc?.streetName,
            district: customerDoc?.district,
            city: customerDoc?.city,
            postalCode: customerDoc?.postalCode,
            countryCode: customerDoc?.countryCode || 'SA',
            otherId: customerDoc?.otherId ? {
              id: customerDoc.otherId,
              type: customerDoc.otherIdType || 'CRN'
            } : undefined
          },
          lineItems: [{
            name: carDoc ? `${carDoc.brand} ${carDoc.carModel || (carDoc as any).model} - Plate: ${carDoc.plateNumber || '-'} - VIN: ${carDoc.chassisNumber || '-'}`.trim() : sale.carId,
            quantity: 1,
            unitPrice: sale.finalPrice,
            vatRate: sale.vatRate || 0,
            vatAmount: sale.vatAmount || 0,
            totalAmount: sale.finalPriceWithVat || sale.finalPrice,
          }],
          subtotal: sale.finalPrice,
          vatTotal: sale.vatAmount || 0,
          totalWithVat: sale.finalPriceWithVat || sale.finalPrice,
          notes: sale.notes,
          createdBy: user.userId,
        });
        await CashSale.findByIdAndUpdate(sale._id, {
          zatcaUUID: zatcaResult.uuid,
          zatcaQRCode: zatcaResult.qrCode,
          zatcaHash: zatcaResult.xmlHash,
          zatcaStatus: zatcaResult.status,
          zatcaResponse: zatcaResult.zatcaResponse,
          applyVat: sale.applyVat,
          vatRate: sale.vatRate,
          vatInclusive: sale.vatInclusive,
          vatAmount: sale.vatAmount,
          finalPriceWithVat: sale.finalPriceWithVat,
        });
      } catch (zatcaError) {
        console.error('ZATCA reprocessing failed:', zatcaError);
      }
    }

    await logActivity({
      userId: user.userId,
      userName: user.name,
      action: `Updated cash sale: ${sale.saleId}`,
      module: 'Sales',
      targetId: sale._id.toString(),
      ipAddress: request.headers.get('x-forwarded-for') || 'unknown',
    });

    const updatedSale = await CashSale.findById(sale._id).lean();
    return NextResponse.json({ sale: updatedSale });
  } catch (error) {
    console.error('Update cash sale error:', error);

    if (error instanceof DatabaseConnectionError) {
      return NextResponse.json({ error: error.message }, { status: error.statusCode });
    }

    return NextResponse.json({ error: 'Internal server error' }, { status: 500 });
  }
}

export async function DELETE(
  request: NextRequest,
  { params }: { params: Promise<{ id: string }> }
) {
  try {
    const { id } = await params;
    const user = await getAuthPayload(request);
    if (!user) {
      return NextResponse.json({ error: 'Unauthorized' }, { status: 401 });
    }

    if (!user.normalizedRoles.some(r => ['Admin', 'Sales Person'].includes(r))) {
      return NextResponse.json({ error: 'Forbidden' }, { status: 403 });
    }

    await connectDB();

    if (!mongoose.Types.ObjectId.isValid(id)) {
      return NextResponse.json({ error: 'Invalid sale ID' }, { status: 400 });
    }

    const sale = await CashSale.findById(id);
    if (!sale) {
      return NextResponse.json({ error: 'Sale not found' }, { status: 404 });
    }

    if (sale.status === 'Cancelled') {
      return NextResponse.json({ error: 'Sale already cancelled' }, { status: 400 });
    }

    // Soft delete
    await CashSale.findByIdAndUpdate(id, { isDeleted: true });

    await Promise.all([
      Car.findByIdAndUpdate(sale.car, {
        status: 'In Stock',
        tafweedStatus: 'None',
        tafweedAuthorizedTo: '',
        tafweedDriverIqama: '',
        tafweedDurationMonths: null,
        tafweedExpiryDate: null,
      }),
      Transaction.findOneAndUpdate(
        { referenceId: sale._id.toString(), referenceType: 'CashSale', isAutoGenerated: true },
        { isDeleted: true }
      ),
    ]);

    await logActivity({
      userId: user.userId,
      userName: user.name,
      action: `Deleted cash sale: ${sale.saleId}`,
      module: 'Sales',
      targetId: id,
      ipAddress: request.headers.get('x-forwarded-for') || 'unknown',
    });

    return NextResponse.json({ message: 'Sale deleted successfully' });
  } catch (error) {
    console.error('Delete cash sale error:', error);

    if (error instanceof DatabaseConnectionError) {
      return NextResponse.json({ error: error.message }, { status: error.statusCode });
    }

    return NextResponse.json({ error: 'Internal server error' }, { status: 500 });
  }
}

export async function PATCH(
  request: NextRequest,
  { params }: { params: Promise<{ id: string }> }
) {
  try {
    const { id } = await params;
    const user = await getAuthPayload(request);
    if (!user) {
      return NextResponse.json({ error: 'Unauthorized' }, { status: 401 });
    }

    if (!user.normalizedRoles.some(r => ['Admin', 'Sales Person'].includes(r))) {
      return NextResponse.json({ error: 'Forbidden' }, { status: 403 });
    }

    await connectDB();

    if (!mongoose.Types.ObjectId.isValid(id)) {
      return NextResponse.json({ error: 'Invalid sale ID' }, { status: 400 });
    }

    const body = await request.json();
    const { action } = body;

    if (action === 'generate-invoice') {
      const sale = await CashSale.findById(id);
      if (!sale) {
        return NextResponse.json({ error: 'Sale not found' }, { status: 404 });
      }

      const [carData, customerData] = await Promise.all([
        Car.findById(sale.car).lean() as unknown as ICarRaw,
        sale.customer ? Customer.findById(sale.customer).lean() as unknown as ICustomerDocument : null,
      ]);

      const invoiceUrl = await generateInvoice({
        saleId: sale.saleId,
        saleDate: sale.saleDate.toString(),
        carId: sale.carId,
        carBrand: carData?.brand,
        carModel: (carData as any)?.carModel || (carData as any)?.model,
        carYear: carData?.year,
        carPlate: carData?.plateNumber,
        carVin: carData?.chassisNumber,
        carEngineNumber: carData?.engineNumber,
        carSequenceNumber: carData?.sequenceNumber,
        carColor: carData?.color,
        customerName: sale.customerName || 'Cash Customer',
        customerPhone: sale.customerPhone || '',
        customerId: (customerData as any)?.otherId || (customerData as any)?.customerId || '',
        customerAddress: customerData ? `${customerData.buildingNumber || ''} ${customerData.streetName || ''}, ${customerData.district || ''}, ${customerData.city || ''} ${customerData.postalCode || ''}`.trim() : '',
        salePrice: sale.salePrice,
        discountType: sale.discountType,
        discountValue: sale.discountValue,
        discountAmount: sale.discountAmount,
        finalPrice: sale.finalPrice,
        vatRate: sale.vatRate || 0,
        vatAmount: sale.vatAmount || 0,
        finalPriceWithVat: sale.finalPriceWithVat || sale.finalPrice,
        agentName: sale.agentName,
        agentCommission: sale.agentCommission,
        zatcaQRCode: sale.zatcaQRCode,
        zatcaUUID: sale.zatcaUUID,
        invoiceType: sale.invoiceType || 'Simplified',
      });

      sale.invoiceUrl = `${invoiceUrl}?t=${Date.now()}`;
      await sale.save();

      await logActivity({
        userId: user.userId,
        userName: user.name,
        action: `Regenerated invoice for cash sale: ${sale.saleId}`,
        module: 'Sales',
        targetId: sale._id.toString(),
        ipAddress: request.headers.get('x-forwarded-for') || 'unknown',
      });

      return NextResponse.json({ invoiceUrl, sale });
    }

    return NextResponse.json({ error: 'Invalid action' }, { status: 400 });
  } catch (error) {
    console.error('Patch cash sale error:', error);

    if (error instanceof DatabaseConnectionError) {
      return NextResponse.json({ error: error.message }, { status: error.statusCode });
    }

    return NextResponse.json({ error: 'Internal server error' }, { status: 500 });
  }
}
