import { NextRequest, NextResponse } from 'next/server';
import mongoose from 'mongoose';
import { connectDB, DatabaseConnectionError } from '@/lib/db';
import { getAuthPayload } from '@/lib/apiAuth';
import PurchaseReturn from '@/models/PurchaseReturn';
import Customer from '@/models/Customer';
import User from '@/models/User';
import Car from '@/models/Car';
import { logActivity } from '@/lib/activityLogger';

export async function GET(
  request: NextRequest,
  { params }: { params: Promise<{ id: string }> }
) {
  try {
    const auth = await getAuthPayload(request);
    if (!auth) {
      return NextResponse.json({ error: 'Unauthorized' }, { status: 401 });
    }

    if (!auth.normalizedRoles.some(r => ['Admin', 'Sales Person', 'Accountant', 'Finance Manager'].includes(r))) {
      return NextResponse.json({ error: 'Forbidden' }, { status: 403 });
    }

    const { id } = await params;
    await connectDB();

    const returnItem = await PurchaseReturn.findById(id)
      .populate('car', 'carId brand model year plateNumber chassisNumber engineNumber sequenceNumber color images')
      .populate('customer', 'fullName phone profilePhoto')
      .populate('createdBy', 'name')
      .populate('approvedBy', 'name')
      .lean();

    if (!returnItem) {
      return NextResponse.json({ error: 'Return not found' }, { status: 404 });
    }

    return NextResponse.json({ return: returnItem });
  } catch (error) {
    console.error('Purchase Return GET error:', error);
    return NextResponse.json({ error: 'Failed to fetch return' }, { status: 500 });
  }
}

export async function PUT(
  request: NextRequest,
  { params }: { params: Promise<{ id: string }> }
) {
  try {
    const auth = await getAuthPayload(request);
    if (!auth) {
      return NextResponse.json({ error: 'Unauthorized' }, { status: 401 });
    }

    if (!auth.normalizedRoles.some(r => ['Admin', 'Sales Person', 'Accountant', 'Finance Manager'].includes(r))) {
      return NextResponse.json({ error: 'Forbidden' }, { status: 403 });
    }

    const { id } = await params;
    const body = await request.json();
    const { status, penaltyAmount, conditionNotes, notes } = body;

    await connectDB();

    const returnItem = await PurchaseReturn.findById(id);
    if (!returnItem) {
      return NextResponse.json({ error: 'Return not found' }, { status: 404 });
    }

    const updateData: Record<string, unknown> = {};
    if (status) {
      updateData.status = status;
      if (status === 'Approved' || status === 'Rejected') {
        updateData.approvedBy = new mongoose.Types.ObjectId(auth.userId);
        updateData.approvedAt = new Date();
      }
      if (status === 'Completed' && returnItem.status !== 'Completed') {
        updateData.status = 'Completed';
        
        await Car.findByIdAndUpdate(returnItem.car, { status: 'In Stock' });
        
        if (returnItem.saleType === 'Cash') {
          const CashSale = (await import('@/models/CashSale')).default;
          await CashSale.findByIdAndUpdate(returnItem.originalSale, { status: 'Cancelled' });
        } else if (returnItem.saleType === 'Installment') {
          const InstallmentSale = (await import('@/models/InstallmentSale')).default;
          await InstallmentSale.findByIdAndUpdate(returnItem.originalSale, { status: 'Cancelled' });
        } else if (returnItem.saleType === 'Rental') {
          const Rental = (await import('@/models/Rental')).default;
          await Rental.findByIdAndUpdate(returnItem.originalSale, { status: 'Cancelled' });
        }

        const Transaction = (await import('@/models/Transaction')).default;
        
        if (returnItem.refundAmount > 0) {
          await Transaction.create({
            date: new Date(),
            type: 'Expense',
            category: 'Refund',
            amount: returnItem.refundAmount,
            description: `Refund for return ${returnItem.returnId}`,
            referenceId: returnItem._id.toString(),
            referenceType: 'PurchaseReturn',
            isAutoGenerated: true,
            createdBy: new mongoose.Types.ObjectId(auth.userId),
          });
        }
        
        const finalPenalty = penaltyAmount !== undefined ? penaltyAmount : returnItem.penaltyAmount;
        if (finalPenalty && finalPenalty > 0) {
           await Transaction.create({
            date: new Date(),
            type: 'Income',
            category: 'Fee',
            amount: finalPenalty,
            description: `Penalty for return ${returnItem.returnId}`,
            referenceId: returnItem._id.toString(),
            referenceType: 'PurchaseReturn',
            isAutoGenerated: true,
            createdBy: new mongoose.Types.ObjectId(auth.userId),
          });
        }
      }
    }
    if (penaltyAmount !== undefined) updateData.penaltyAmount = penaltyAmount;
    if (conditionNotes !== undefined) updateData.conditionNotes = conditionNotes;
    if (notes !== undefined) updateData.notes = notes;

    const updated = await PurchaseReturn.findByIdAndUpdate(
      id,
      { $set: updateData },
      { new: true }
    )
      .populate('car', 'carId brand model images')
      .populate('customer', 'fullName phone profilePhoto')
      .lean();

    return NextResponse.json({ return: updated });
  } catch (error) {
    console.error('Purchase Return PUT error:', error);
    return NextResponse.json({ error: 'Failed to update return' }, { status: 500 });
  }
}

export async function DELETE(
  request: NextRequest,
  { params }: { params: Promise<{ id: string }> }
) {
  try {
    const auth = await getAuthPayload(request);
    if (!auth) {
      return NextResponse.json({ error: 'Unauthorized' }, { status: 401 });
    }

    if (!auth.normalizedRoles.some(r => ['Admin', 'Sales Person', 'Accountant', 'Finance Manager'].includes(r))) {
      return NextResponse.json({ error: 'Forbidden' }, { status: 403 });
    }

    const { id } = await params;
    await connectDB();

    const returnItem = await PurchaseReturn.findById(id);
    if (!returnItem) {
      return NextResponse.json({ error: 'Return not found' }, { status: 404 });
    }

    if (returnItem.status !== 'Pending') {
      return NextResponse.json(
        { error: 'Can only delete pending returns' },
        { status: 400 }
      );
    }

    await PurchaseReturn.findByIdAndDelete(id);

    await logActivity({
      userId: auth.userId,
      userName: auth.name,
      action: 'Deleted return',
      module: 'Return',
      targetId: id,
      ipAddress: request.headers.get('x-forwarded-for') || 'unknown',
    });

    return NextResponse.json({ success: true });
  } catch (error) {
    console.error('Purchase Return DELETE error:', error);
    return NextResponse.json({ error: 'Failed to delete return' }, { status: 500 });
  }
}
