import { NextRequest, NextResponse } from 'next/server';
import { connectDB, DatabaseConnectionError } from '@/lib/db';
import Rental from '@/models/Rental';
import Car from '@/models/Car';
import Transaction from '@/models/Transaction';
import { getAuthPayload } from '@/lib/apiAuth';
import { logActivity } from '@/lib/activityLogger';
import mongoose from 'mongoose';

export async function GET(
  request: NextRequest,
  { params }: { params: Promise<{ id: string }> }
) {
  try {
    const { id } = await params;
    const user = await getAuthPayload(request);
    if (!user) {
      return NextResponse.json({ error: 'Unauthorized' }, { status: 401 });
    }

    await connectDB();

    const rental = await Rental.findById(id).lean();
    if (!rental) {
      return NextResponse.json({ error: 'Rental not found' }, { status: 404 });
    }

    return NextResponse.json({ rental });
  } catch (error) {
    console.error('Get rental error:', error);

    if (error instanceof DatabaseConnectionError) {
      return NextResponse.json({ error: error.message }, { status: error.statusCode });
    }

    return NextResponse.json({ error: 'Internal server error' }, { status: 500 });
  }
}

export async function PUT(
  request: NextRequest,
  { params }: { params: Promise<{ id: string }> }
) {
  try {
    const { id } = await params;
    const user = await getAuthPayload(request);
    if (!user) {
      return NextResponse.json({ error: 'Unauthorized' }, { status: 401 });
    }

    await connectDB();

    if (!mongoose.Types.ObjectId.isValid(id)) {
      return NextResponse.json({ error: 'Invalid rental ID' }, { status: 400 });
    }

    const rental = await Rental.findById(id);
    if (!rental) {
      return NextResponse.json({ error: 'Rental not found' }, { status: 404 });
    }

    if (rental.status === 'Cancelled') {
      return NextResponse.json({ error: 'Cannot update cancelled rental' }, { status: 400 });
    }

    const body = await request.json();
    const { dailyRate, securityDeposit, returnDate, actualReturnDate, notes, status } = body;

    if (status !== undefined && (status === 'Completed' || status === 'Cancelled')) {
      const currentStatus = (rental.status as string) || 'Active';
      if (currentStatus === 'Completed' || currentStatus === 'Cancelled') {
        return NextResponse.json({ error: 'Rental already closed' }, { status: 400 });
      }

      rental.status = status;
      await rental.save();

      // Update car back to In Stock when rental is completed or cancelled
      await Car.findByIdAndUpdate(rental.car, { status: 'In Stock' });

      // Soft delete related transaction
      await Transaction.findOneAndUpdate(
        { referenceId: rental._id.toString(), referenceType: 'Rental', isAutoGenerated: true },
        { isDeleted: true }
      );

      await logActivity({
        userId: user.userId,
        userName: user.name,
        action: `Closed rental: ${rental.rentalId} - Car returned`,
        module: 'Rental',
        targetId: rental._id.toString(),
        ipAddress: request.headers.get('x-forwarded-for') || 'unknown',
      });

      return NextResponse.json({ rental });
    }

    if (dailyRate !== undefined) rental.dailyRate = dailyRate;
    if (securityDeposit !== undefined) rental.securityDeposit = securityDeposit;
    if (returnDate !== undefined) rental.returnDate = new Date(returnDate);
    if (actualReturnDate !== undefined) rental.actualReturnDate = new Date(actualReturnDate);
    if (notes !== undefined) rental.notes = notes;

    await rental.save();

    await logActivity({
      userId: user.userId,
      userName: user.name,
      action: `Updated rental: ${rental.rentalId}`,
      module: 'Rental',
      targetId: rental._id.toString(),
      ipAddress: request.headers.get('x-forwarded-for') || 'unknown',
    });

    return NextResponse.json({ rental });
  } catch (error) {
    console.error('Update rental error:', error);

    if (error instanceof DatabaseConnectionError) {
      return NextResponse.json({ error: error.message }, { status: error.statusCode });
    }

    return NextResponse.json({ error: 'Internal server error' }, { status: 500 });
  }
}

export async function DELETE(
  request: NextRequest,
  { params }: { params: Promise<{ id: string }> }
) {
  try {
    const { id } = await params;
    const user = await getAuthPayload(request);
    if (!user) {
      return NextResponse.json({ error: 'Unauthorized' }, { status: 401 });
    }

    await connectDB();

    if (!mongoose.Types.ObjectId.isValid(id)) {
      return NextResponse.json({ error: 'Invalid rental ID' }, { status: 400 });
    }

    const rental = await Rental.findById(id);
    if (!rental) {
      return NextResponse.json({ error: 'Rental not found' }, { status: 404 });
    }

    if (rental.status === 'Cancelled') {
      return NextResponse.json({ error: 'Rental already cancelled' }, { status: 400 });
    }

    // Soft delete - mark as cancelled
    rental.status = 'Cancelled';
    await rental.save();

    // Update car back to available
    await Car.findByIdAndUpdate(rental.car, { status: 'In Stock' });

    // Soft delete related transactions
    await Transaction.updateMany(
      { referenceId: rental._id.toString(), referenceType: 'Rental', isAutoGenerated: true },
      { isDeleted: true }
    );

    await logActivity({
      userId: user.userId,
      userName: user.name,
      action: `Cancelled rental: ${rental.rentalId}`,
      module: 'Rental',
      targetId: rental._id.toString(),
      ipAddress: request.headers.get('x-forwarded-for') || 'unknown',
    });

    return NextResponse.json({ message: 'Rental cancelled successfully' });
  } catch (error) {
    console.error('Delete rental error:', error);

    if (error instanceof DatabaseConnectionError) {
      return NextResponse.json({ error: error.message }, { status: error.statusCode });
    }

    return NextResponse.json({ error: 'Internal server error' }, { status: 500 });
  }
}