import { NextRequest, NextResponse } from 'next/server';
import { connectDB, DatabaseConnectionError } from '@/lib/db';
import Rental from '@/models/Rental';
import Car from '@/models/Car';
import Customer from '@/models/Customer';
import Transaction from '@/models/Transaction';
import { getAuthPayload } from '@/lib/apiAuth';
import { logActivity } from '@/lib/activityLogger';
import { processZatcaInvoice, calculateVat, ZATCA_VAT_RATE } from '@/lib/zatca/invoiceService';
import mongoose from 'mongoose';

export async function GET(
  request: NextRequest,
  { params }: { params: Promise<{ id: string }> }
) {
  try {
    const { id } = await params;
    const user = await getAuthPayload(request);
    if (!user) {
      return NextResponse.json({ error: 'Unauthorized' }, { status: 401 });
    }

    if (!['Admin', 'Sales Person'].includes(user.normalizedRole || '')) {
      return NextResponse.json({ error: 'Forbidden' }, { status: 403 });
    }

    await connectDB();

    const rental = await Rental.findById(id).lean();
    if (!rental) {
      return NextResponse.json({ error: 'Rental not found' }, { status: 404 });
    }

    return NextResponse.json({ rental });
  } catch (error) {
    console.error('Get rental error:', error);

    if (error instanceof DatabaseConnectionError) {
      return NextResponse.json({ error: error.message }, { status: error.statusCode });
    }

    return NextResponse.json({ error: 'Internal server error' }, { status: 500 });
  }
}

export async function PUT(
  request: NextRequest,
  { params }: { params: Promise<{ id: string }> }
) {
  try {
    const { id } = await params;
    const user = await getAuthPayload(request);
    if (!user) {
      return NextResponse.json({ error: 'Unauthorized' }, { status: 401 });
    }

    if (!['Admin', 'Sales Person'].includes(user.normalizedRole || '')) {
      return NextResponse.json({ error: 'Forbidden' }, { status: 403 });
    }

    await connectDB();

    if (!mongoose.Types.ObjectId.isValid(id)) {
      return NextResponse.json({ error: 'Invalid rental ID' }, { status: 400 });
    }

    const rental = await Rental.findById(id);
    if (!rental) {
      return NextResponse.json({ error: 'Rental not found' }, { status: 404 });
    }

    if (rental.status === 'Cancelled') {
      return NextResponse.json({ error: 'Cannot update cancelled rental' }, { status: 400 });
    }

    const body = await request.json();
    const { dailyRate, securityDeposit, returnDate, actualReturnDate, notes, status, invoiceType, buyerTrn, agentName, agentCommission } = body;

    if (status !== undefined && (status === 'Completed' || status === 'Cancelled')) {
      const currentStatus = (rental.status as string) || 'Active';
      if (currentStatus === 'Completed' || currentStatus === 'Cancelled') {
        return NextResponse.json({ error: 'Rental already closed' }, { status: 400 });
      }

      rental.status = status;
      await rental.save();

      // Update car back to In Stock when rental is completed or cancelled
      await Car.findByIdAndUpdate(rental.car, { status: 'In Stock' });

      // Soft delete related transaction
      await Transaction.findOneAndUpdate(
        { referenceId: rental._id.toString(), referenceType: 'Rental', isAutoGenerated: true },
        { isDeleted: true }
      );

      await logActivity({
        userId: user.userId,
        userName: user.name,
        action: `Closed rental: ${rental.rentalId} - Car returned`,
        module: 'Rental',
        targetId: rental._id.toString(),
        ipAddress: request.headers.get('x-forwarded-for') || 'unknown',
      });

      return NextResponse.json({ rental });
    }

    if (dailyRate !== undefined) rental.dailyRate = dailyRate;
    if (securityDeposit !== undefined) rental.securityDeposit = securityDeposit;
    if (returnDate !== undefined) rental.returnDate = new Date(returnDate);
    if (actualReturnDate !== undefined) rental.actualReturnDate = new Date(actualReturnDate);
    if (notes !== undefined) rental.notes = notes;
    if (agentName !== undefined) (rental as any).agentName = agentName;
    if (agentCommission !== undefined) (rental as any).agentCommission = agentCommission;

    const zatcaFieldChanged = invoiceType !== undefined || buyerTrn !== undefined;
    if (invoiceType !== undefined) rental.invoiceType = invoiceType;
    if (buyerTrn !== undefined) (rental as any).buyerTrn = buyerTrn;

    await rental.save();

    // Re-run ZATCA if invoiceType or buyerTrn changed
    if (zatcaFieldChanged) {
      try {
        const [customerDoc, carDoc] = await Promise.all([
          Customer.findById(rental.customer).lean(),
          Car.findById(rental.car).lean(),
        ]);
        const days = Math.ceil((new Date(rental.endDate).getTime() - new Date(rental.startDate).getTime()) / (1000 * 60 * 60 * 24));
        const vatInfo = calculateVat(rental.totalAmount, ZATCA_VAT_RATE);
        const rentalDesc = carDoc
          ? `Rental - ${carDoc.brand} ${carDoc.model} (${days} days)`.trim()
          : `Rental - ${rental.carId} (${days} days)`;
        const zatcaResult = await processZatcaInvoice({
          referenceId: rental._id.toString(),
          referenceType: 'Rental',
          saleId: rental.rentalId,
          invoiceType: (rental.invoiceType as 'Standard' | 'Simplified') || 'Simplified',
          issueDate: new Date(rental.startDate),
          buyer: {
            name: rental.customerName,
            trn: (rental as any).buyerTrn || '',
            address: customerDoc?.address,
            city: '',
          },
          lineItems: [{
            name: rentalDesc,
            quantity: days,
            unitPrice: rental.dailyRate,
            vatRate: ZATCA_VAT_RATE,
            vatAmount: vatInfo.vatAmount,
            totalAmount: vatInfo.totalWithVat,
          }],
          subtotal: vatInfo.subtotal,
          vatTotal: vatInfo.vatAmount,
          totalWithVat: vatInfo.totalWithVat,
          notes: rental.notes,
          createdBy: user.userId,
        });
        await Rental.findByIdAndUpdate(rental._id, {
          zatcaUUID: zatcaResult.uuid,
          zatcaQRCode: zatcaResult.qrCode,
          zatcaHash: zatcaResult.xmlHash,
          zatcaStatus: zatcaResult.status,
          zatcaResponse: zatcaResult.zatcaResponse,
          vatAmount: vatInfo.vatAmount,
        });
      } catch (zatcaError) {
        console.error('ZATCA reprocessing failed:', zatcaError);
      }
    }

    await logActivity({
      userId: user.userId,
      userName: user.name,
      action: `Updated rental: ${rental.rentalId}`,
      module: 'Rental',
      targetId: rental._id.toString(),
      ipAddress: request.headers.get('x-forwarded-for') || 'unknown',
    });

    return NextResponse.json({ rental });
  } catch (error) {
    console.error('Update rental error:', error);

    if (error instanceof DatabaseConnectionError) {
      return NextResponse.json({ error: error.message }, { status: error.statusCode });
    }

    return NextResponse.json({ error: 'Internal server error' }, { status: 500 });
  }
}

export async function DELETE(
  request: NextRequest,
  { params }: { params: Promise<{ id: string }> }
) {
  try {
    const { id } = await params;
    const user = await getAuthPayload(request);
    if (!user) {
      return NextResponse.json({ error: 'Unauthorized' }, { status: 401 });
    }

    if (!['Admin', 'Sales Person'].includes(user.normalizedRole || '')) {
      return NextResponse.json({ error: 'Forbidden' }, { status: 403 });
    }

    await connectDB();

    if (!mongoose.Types.ObjectId.isValid(id)) {
      return NextResponse.json({ error: 'Invalid rental ID' }, { status: 400 });
    }

    const rental = await Rental.findById(id);
    if (!rental) {
      return NextResponse.json({ error: 'Rental not found' }, { status: 404 });
    }

    if (rental.status === 'Cancelled') {
      return NextResponse.json({ error: 'Rental already cancelled' }, { status: 400 });
    }

    // Soft delete - mark as cancelled
    rental.status = 'Cancelled';
    await Promise.all([
      rental.save(),
      Car.findByIdAndUpdate(rental.car, { status: 'In Stock' }),
      Transaction.updateMany(
        { referenceId: rental._id.toString(), referenceType: 'Rental', isAutoGenerated: true },
        { isDeleted: true }
      ),
    ]);

    await logActivity({
      userId: user.userId,
      userName: user.name,
      action: `Cancelled rental: ${rental.rentalId}`,
      module: 'Rental',
      targetId: rental._id.toString(),
      ipAddress: request.headers.get('x-forwarded-for') || 'unknown',
    });

    return NextResponse.json({ message: 'Rental cancelled successfully' });
  } catch (error) {
    console.error('Delete rental error:', error);

    if (error instanceof DatabaseConnectionError) {
      return NextResponse.json({ error: error.message }, { status: error.statusCode });
    }

    return NextResponse.json({ error: 'Internal server error' }, { status: 500 });
  }
}
