import { NextRequest, NextResponse } from 'next/server';
import { connectDB, DatabaseConnectionError } from '@/lib/db';
import CashSale from '@/models/CashSale';
import Car from '@/models/Car';
import Customer from '@/models/Customer';
import Transaction from '@/models/Transaction';
import { getAuthPayload } from '@/lib/apiAuth';
import { logActivity } from '@/lib/activityLogger';
import { generateInvoice } from '@/lib/invoiceGenerator';
import { sendSaleThankYouNotifications } from '@/lib/saleNotifications';
import { processZatcaInvoice, calculateVat, ZATCA_VAT_RATE } from '@/lib/zatca/invoiceService';
import mongoose from 'mongoose';

export async function GET(request: NextRequest) {
  try {
    await connectDB();
    const user = await getAuthPayload(request);
    if (!user) {
      return NextResponse.json({ error: 'Unauthorized' }, { status: 401 });
    }

    const { searchParams } = new URL(request.url);
    const page = parseInt(searchParams.get('page') || '1');
    const limit = parseInt(searchParams.get('limit') || '15');
    const search = searchParams.get('search') || '';
    const customerId = searchParams.get('customer');

    const statusFilter = {
      $or: [
        { status: 'Active' },
        { status: { $exists: false } }
      ]
    };

    let query: Record<string, unknown> = { ...statusFilter };

    if (customerId) {
      query.customer = new mongoose.Types.ObjectId(customerId);
    }

    if (search) {
      query = {
        $and: [
          statusFilter,
          {
            $or: [
              { customerName: { $regex: search, $options: 'i' } },
              { carId: { $regex: search, $options: 'i' } },
              { saleId: { $regex: search, $options: 'i' } },
            ]
          }
        ]
      };
      if (customerId) {
        (query.$and as Record<string, unknown>[]).push({ customer: new mongoose.Types.ObjectId(customerId) });
      }
    }

    const skip = (page - 1) * limit;
    const [sales, total] = await Promise.all([
      CashSale.find(query)
        .sort({ saleDate: -1 })
        .skip(skip)
        .limit(limit)
        .populate('car', 'carId brand model images')
        .populate('customer', 'fullName phone profilePhoto')
        .lean(),
      CashSale.countDocuments(query),
    ]);

    // Calculate totals
    const totalRevenue = await CashSale.aggregate([
      { $match: query },
      { $group: { _id: null, total: { $sum: '$finalPrice' } } },
    ]);

    return NextResponse.json({
      sales,
      pagination: { page, limit, total, pages: Math.ceil(total / limit) },
      totalRevenue: totalRevenue[0]?.total || 0,
    });
  } catch (error) {
    console.error('Get cash sales error:', error);
    if (error instanceof DatabaseConnectionError) {
      return NextResponse.json({ error: error.message }, { status: error.statusCode });
    }
    return NextResponse.json({ error: 'Internal server error' }, { status: 500 });
  }
}

export async function POST(request: NextRequest) {
  try {
    await connectDB();
    const user = await getAuthPayload(request);
    if (!user) {
      return NextResponse.json({ error: 'Unauthorized' }, { status: 401 });
    }

    const body = await request.json();
    const {
      carId, car, customer, customerName, customerPhone,
      salePrice, discountType = 'flat', discountValue = 0, agentName, agentCommission,
      saleDate, notes,
      invoiceType = 'Simplified',
      buyerTrn,
    } = body;

    if (!carId || !car || !customer || !customerName || !customerPhone || !salePrice || !saleDate) {
      return NextResponse.json({ error: 'Required fields missing' }, { status: 400 });
    }

    const computedDiscountAmount = discountType === 'percentage'
      ? Math.round(salePrice * (discountValue || 0) / 100 * 100) / 100
      : (discountValue || 0);
    const finalPrice = salePrice - computedDiscountAmount;
    const { vatAmount, totalWithVat } = calculateVat(finalPrice, ZATCA_VAT_RATE);

    const sale = await CashSale.create({
      car: car,
      carId,
      customer,
      customerName,
      customerPhone,
      salePrice,
      discountType,
      discountValue: discountValue || 0,
      discountAmount: computedDiscountAmount,
      finalPrice,
      vatRate: ZATCA_VAT_RATE,
      vatAmount,
      finalPriceWithVat: totalWithVat,
      agentName,
      agentCommission: agentCommission || 0,
      saleDate,
      notes,
      invoiceType,
      zatcaStatus: 'Pending',
      createdBy: user.userId,
    });

    // Update car status to Sold
    await Car.findByIdAndUpdate(car, { status: 'Sold' });

    // Create income transaction
    await Transaction.create({
      date: new Date(saleDate),
      type: 'Income',
      category: 'Cash Sale',
      amount: finalPrice,
      description: `Cash sale ${sale.saleId} - Car ${carId}`,
      referenceId: sale._id.toString(),
      referenceType: 'CashSale',
      isAutoGenerated: true,
      createdBy: user.userId,
    });

    await logActivity({
      userId: user.userId,
      userName: user.name,
      action: `Created cash sale: ${sale.saleId} for car ${carId}`,
      module: 'Sales',
      targetId: sale._id.toString(),
      ipAddress: request.headers.get('x-forwarded-for') || 'unknown',
    });

    // Generate invoice PDF
    let invoiceUrl = '';
    const customerData = await Customer.findById(customer).lean();
    const carData = await Car.findById(car).lean();

    // Process ZATCA invoice
    let zatcaResult;
    try {
      zatcaResult = await processZatcaInvoice({
        referenceId: sale._id.toString(),
        referenceType: 'CashSale',
        saleId: sale.saleId,
        invoiceType,
        issueDate: new Date(saleDate),
        buyer: {
          name: customerName,
          trn: buyerTrn,
          address: customerData?.address,
          city: '',
        },
        lineItems: [{
          name: `${carData?.brand || ''} ${carData?.model || ''} (${carId})`.trim(),
          quantity: 1,
          unitPrice: finalPrice,
          vatRate: ZATCA_VAT_RATE,
          vatAmount,
          totalAmount: totalWithVat,
        }],
        subtotal: finalPrice,
        vatTotal: vatAmount,
        totalWithVat,
        discountAmount: computedDiscountAmount,
        notes,
        createdBy: user.userId,
      });

      sale.zatcaUUID = zatcaResult.uuid;
      sale.zatcaQRCode = zatcaResult.qrCode;
      sale.zatcaStatus = zatcaResult.status as 'Pending' | 'Cleared' | 'Reported' | 'Failed' | 'NotRequired';
      sale.zatcaHash = zatcaResult.xmlHash;
      sale.zatcaResponse = zatcaResult.zatcaResponse;
      await sale.save();
    } catch (zatcaError) {
      console.error('ZATCA processing failed:', zatcaError);
    }

    try {
      invoiceUrl = await generateInvoice({
        saleId: sale.saleId,
        saleDate: sale.saleDate.toString(),
        carId: sale.carId,
        carBrand: carData?.brand,
        carModel: carData?.model,
        customerName: sale.customerName,
        customerPhone: sale.customerPhone,
        customerAddress: customerData?.address,
        salePrice: sale.salePrice,
        discountType: sale.discountType,
        discountValue: sale.discountValue,
        discountAmount: sale.discountAmount,
        finalPrice: sale.finalPrice,
        vatRate: sale.vatRate,
        vatAmount: sale.vatAmount,
        finalPriceWithVat: sale.finalPriceWithVat,
        agentName: sale.agentName,
        agentCommission: sale.agentCommission,
        zatcaQRCode: zatcaResult?.qrCode,
        zatcaUUID: zatcaResult?.uuid,
        invoiceType,
      });

      sale.invoiceUrl = invoiceUrl;
      await sale.save();
    } catch (invoiceError) {
      console.error('Invoice generation failed:', invoiceError);
    }

    // Send thank-you notifications to customer
    try {
      await sendSaleThankYouNotifications(
        {
          name: customerName,
          phone: customerPhone,
          email: customerData?.email,
        },
        {
          saleId: sale.saleId,
          carId: sale.carId,
          carBrand: carData?.brand,
          carModel: carData?.model,
          finalPrice: sale.finalPrice,
        }
      );
    } catch (notifyError) {
      console.error('Customer notification failed:', notifyError);
    }

    return NextResponse.json({ sale, invoiceUrl, zatcaStatus: zatcaResult?.status }, { status: 201 });
  } catch (error) {
    console.error('Create cash sale error:', error);
    if (error instanceof DatabaseConnectionError) {
      return NextResponse.json({ error: error.message }, { status: error.statusCode });
    }
    return NextResponse.json({ error: 'Internal server error' }, { status: 500 });
  }
}