import { NextRequest, NextResponse } from 'next/server';
import { connectDB, DatabaseConnectionError, runInTransaction } from '@/lib/db';
import InstallmentSale from '@/models/InstallmentSale';
import Transaction from '@/models/Transaction';
import Car from '@/models/Car';
import { getAuthPayload } from '@/lib/apiAuth';
import { logActivity } from '@/lib/activityLogger';
import { calculateAccruedLateFee } from '@/lib/installmentUtils';
import mongoose from 'mongoose';

export async function POST(
  request: NextRequest,
  { params }: { params: Promise<{ id: string }> }
) {
  try {
    await connectDB();
    const user = await getAuthPayload(request);
    if (!user) {
      return NextResponse.json({ error: 'Unauthorized' }, { status: 401 });
    }

    if (!user.normalizedRoles.some(r => ['Admin', 'Sales Person', 'Accountant', 'Finance Manager'].includes(r))) {
      return NextResponse.json({ error: 'Forbidden' }, { status: 403 });
    }

    const { id } = await params;

    if (!mongoose.Types.ObjectId.isValid(id)) {
      return NextResponse.json({ error: 'Invalid sale ID' }, { status: 400 });
    }

    const body = await request.json();
    const { installmentNumber, amount, lateFeeAmount, paymentDate, notes, method, voucherNumber } = body;

    if (!installmentNumber || amount === undefined || !paymentDate) {
      return NextResponse.json({ error: 'Installment number, amount and payment date are required' }, { status: 400 });
    }

    const updatedSale = await runInTransaction(async (session) => {
      // Find sale first to validate installment exists and state
      const sale = await InstallmentSale.findById(id).session(session);
      if (!sale) {
        throw new Error('Sale not found');
      }

      const instIdx = sale.paymentSchedule.findIndex(p => p.installmentNumber === installmentNumber);
      if (instIdx === -1) {
        throw new Error('Invalid installment number');
      }
      
      const inst = sale.paymentSchedule[instIdx];
      if (inst.status === 'Paid') {
        throw new Error('Installment already paid');
      }

      // Calculate late fee
      const dueDate = new Date(inst.dueDate);
      const pDate = new Date(paymentDate);
      const diffTime = pDate.getTime() - dueDate.getTime();
      const diffDays = Math.floor(diffTime / (1000 * 60 * 60 * 24));
      const finalLateFee = lateFeeAmount !== undefined ? Number(lateFeeAmount) : calculateAccruedLateFee(diffDays, sale.monthlyLateFee);

      // Update the specific installment in the schedule directly
      const targetInst = sale.paymentSchedule[instIdx];
      targetInst.status = 'Paid';
      targetInst.paidDate = new Date(paymentDate);
      targetInst.paidAmount = amount + finalLateFee;
      targetInst.lateFee = finalLateFee;
      targetInst.notes = notes;
      targetInst.method = method || 'Cash';
      targetInst.voucherNumber = voucherNumber || '';

      // Update parent totals
      sale.totalPaid += (amount + finalLateFee);
      sale.remainingAmount = Math.max(0, sale.remainingAmount - amount);
      sale.lateFeeCharged += finalLateFee;

      // Recalculate next payment info based on new state
      const nextUnpaid = sale.paymentSchedule.find(p => p.status !== 'Paid');

      if (nextUnpaid) {
        sale.nextPaymentDate = nextUnpaid.dueDate;
        sale.nextPaymentAmount = nextUnpaid.amount;

        // Check if there are any remaining overdue installments
        const hasOverdue = sale.paymentSchedule.some(p => p.status === 'Overdue');
        if (!hasOverdue && sale.status === 'Defaulted') {
          sale.status = 'Active';
          await Car.findByIdAndUpdate(sale.car, { status: 'On Installment' }, { session });
        } else if (hasOverdue) {
          sale.status = 'Defaulted';
          await Car.findByIdAndUpdate(sale.car, { status: 'Defaulted' }, { session });
        }
      } else {
        sale.status = 'Completed';
        sale.nextPaymentDate = null as unknown as Date;
        sale.nextPaymentAmount = 0;
        await Car.findByIdAndUpdate(sale.car, { status: 'Sold' }, { session });
      }

      // Explicitly mark paymentSchedule as modified for Mongoose array tracking
      sale.markModified('paymentSchedule');
      await sale.save({ session });

      // Create ledger transactions
      const transactions: any[] = [{
        date: new Date(paymentDate),
        type: 'Income',
        category: 'Installment Payment',
        amount: amount,
        description: `Installment #${installmentNumber} base payment for ${sale.saleId} - Car ${sale.carId}`,
        referenceId: sale._id.toString(),
        referenceType: 'InstallmentSale',
        isAutoGenerated: true,
        createdBy: user.userId,
      }];

      if (finalLateFee > 0) {
        transactions.push({
          date: new Date(paymentDate),
          type: 'Income',
          category: 'Fee',
          amount: finalLateFee,
          description: `Late fee collected for installment #${installmentNumber} - Sale ${sale.saleId}`,
          referenceId: sale._id.toString(),
          referenceType: 'InstallmentSale',
          isAutoGenerated: true,
          createdBy: user.userId,
        });
      }

      for (const txData of transactions) {
        await Transaction.create([txData], { session });
      }

      await logActivity({
        userId: user.userId,
        userName: user.name,
        action: `Recorded payment for installment ${installmentNumber} of sale ${sale.saleId} (Base: ${amount}, Fee: ${finalLateFee})`,
        module: 'Sales',
        targetId: sale._id.toString(),
        ipAddress: request.headers.get('x-forwarded-for') || 'unknown',
      });

      return sale;
    });

    return NextResponse.json({ sale: updatedSale });
  } catch (error: any) {
    console.error('Record payment error:', error);
    if (error instanceof DatabaseConnectionError) {
      return NextResponse.json({ error: error.message }, { status: error.statusCode });
    }
    return NextResponse.json({ error: error.message || 'Internal server error' }, { status: 400 });
  }
}
