import { NextRequest, NextResponse } from 'next/server';
import { connectDB, DatabaseConnectionError, runInTransaction } from '@/lib/db';
import InstallmentSale, { IInstallmentSaleDocument } from '@/models/InstallmentSale';
import Transaction from '@/models/Transaction';
import Car from '@/models/Car';
import { getAuthPayload } from '@/lib/apiAuth';
import { logActivity } from '@/lib/activityLogger';
import { calculateAccruedLateFee, recalculateInstallmentTotals } from '@/lib/installmentUtils';
import mongoose, { ClientSession } from 'mongoose';

/**
 * Synchronizes ledger Transaction documents for an installment payment.
 * Ensures transactions are updated, created, or soft-deleted without leaving orphan active records.
 */
async function syncInstallmentTransactions({
  sale,
  installmentNumber,
  baseAmount,
  lateFee,
  paymentDate,
  userId,
  isReverted,
  session,
}: {
  sale: IInstallmentSaleDocument;
  installmentNumber: number;
  baseAmount?: number;
  lateFee?: number;
  paymentDate?: Date | string;
  userId: string;
  isReverted: boolean;
  session?: ClientSession | null;
}) {
  const saleIdStr = sale._id.toString();

  if (isReverted) {
    // Soft delete all transactions related to this installment
    await Transaction.updateMany(
      {
        referenceId: saleIdStr,
        referenceType: 'InstallmentSale',
        isAutoGenerated: true,
        description: { $regex: new RegExp(`Installment #${installmentNumber}\\b|Late fee collected for installment #${installmentNumber}\\b`, 'i') },
      },
      { $set: { isDeleted: true } },
      session ? { session } : {}
    );
    return;
  }

  const pDate = new Date(paymentDate || new Date());
  const effectiveBaseAmount = Number(baseAmount) || 0;
  const effectiveLateFee = Number(lateFee) || 0;

  // 1. Base payment transaction
  const baseFilter = {
    referenceId: saleIdStr,
    referenceType: 'InstallmentSale',
    isAutoGenerated: true,
    category: 'Installment Payment',
    description: { $regex: new RegExp(`Installment #${installmentNumber}\\b`, 'i') },
  };

  const updatedBase = await Transaction.findOneAndUpdate(
    baseFilter,
    {
      $set: {
        amount: effectiveBaseAmount,
        date: pDate,
        isDeleted: false,
      },
    },
    { new: true, session: session || undefined }
  );

  if (!updatedBase && effectiveBaseAmount > 0) {
    await Transaction.create(
      [{
        date: pDate,
        type: 'Income',
        category: 'Installment Payment',
        amount: effectiveBaseAmount,
        description: `Installment #${installmentNumber} base payment for ${sale.saleId} - Car ${sale.carId}`,
        referenceId: saleIdStr,
        referenceType: 'InstallmentSale',
        isAutoGenerated: true,
        isDeleted: false,
        createdBy: mongoose.Types.ObjectId.isValid(userId) ? new mongoose.Types.ObjectId(userId) : userId,
      }],
      { session: session || undefined, ordered: true }
    );
  }

  // 2. Late fee transaction
  const feeFilter = {
    referenceId: saleIdStr,
    referenceType: 'InstallmentSale',
    isAutoGenerated: true,
    category: 'Fee',
    description: { $regex: new RegExp(`installment #${installmentNumber}\\b`, 'i') },
  };

  if (effectiveLateFee > 0) {
    const updatedFee = await Transaction.findOneAndUpdate(
      feeFilter,
      {
        $set: {
          amount: effectiveLateFee,
          date: pDate,
          isDeleted: false,
        },
      },
      { new: true, session: session || undefined }
    );

    if (!updatedFee) {
      await Transaction.create(
        [{
          date: pDate,
          type: 'Income',
          category: 'Fee',
          amount: effectiveLateFee,
          description: `Late fee collected for installment #${installmentNumber} - Sale ${sale.saleId}`,
          referenceId: saleIdStr,
          referenceType: 'InstallmentSale',
          isAutoGenerated: true,
          isDeleted: false,
          createdBy: mongoose.Types.ObjectId.isValid(userId) ? new mongoose.Types.ObjectId(userId) : userId,
        }],
        { session: session || undefined, ordered: true }
      );
    }
  } else {
    await Transaction.updateMany(
      feeFilter,
      { $set: { isDeleted: true } },
      session ? { session } : {}
    );
  }
}

/**
 * Apply recalculations onto the sale document and synchronize Car status.
 */
async function applySaleRecalculations(sale: IInstallmentSaleDocument, session?: ClientSession | null) {
  const recalculated = recalculateInstallmentTotals(sale.loanAmount, sale.paymentSchedule as any);

  sale.totalPaid = recalculated.totalPaid;
  sale.lateFeeCharged = recalculated.lateFeeCharged;
  sale.remainingAmount = recalculated.remainingAmount;
  sale.nextPaymentDate = recalculated.nextPaymentDate as unknown as Date;
  sale.nextPaymentAmount = recalculated.nextPaymentAmount;
  sale.status = recalculated.saleStatus as any;

  sale.markModified('paymentSchedule');
  await sale.save(session ? { session } : undefined);

  if (sale.car) {
    await Car.findByIdAndUpdate(
      sale.car,
      { status: recalculated.carStatus },
      session ? { session } : undefined
    );
  }

  return recalculated;
}

export async function POST(
  request: NextRequest,
  { params }: { params: Promise<{ id: string }> }
) {
  try {
    await connectDB();
    const user = await getAuthPayload(request);
    if (!user) {
      return NextResponse.json({ error: 'Unauthorized' }, { status: 401 });
    }

    if (!user.normalizedRoles.some(r => ['Admin', 'Sales Person', 'Accountant', 'Finance Manager'].includes(r))) {
      return NextResponse.json({ error: 'Forbidden' }, { status: 403 });
    }

    const { id } = await params;
    if (!mongoose.Types.ObjectId.isValid(id)) {
      return NextResponse.json({ error: 'Invalid sale ID' }, { status: 400 });
    }

    const body = await request.json();
    const { installmentNumber, amount, lateFeeAmount, paymentDate, notes, method, voucherNumber } = body;

    if (!installmentNumber || amount === undefined || !paymentDate) {
      return NextResponse.json({ error: 'Installment number, amount and payment date are required' }, { status: 400 });
    }

    const updatedSale = await runInTransaction(async (session) => {
      const sale = await InstallmentSale.findById(id).session(session);
      if (!sale) {
        throw new Error('Sale not found');
      }

      const instIdx = sale.paymentSchedule.findIndex(p => p.installmentNumber === Number(installmentNumber));
      if (instIdx === -1) {
        throw new Error('Invalid installment number');
      }
      
      const inst = sale.paymentSchedule[instIdx];
      if (inst.status === 'Paid') {
        throw new Error('Installment already paid');
      }

      const dueDate = new Date(inst.dueDate);
      const pDate = new Date(paymentDate);
      const diffTime = pDate.getTime() - dueDate.getTime();
      const diffDays = Math.floor(diffTime / (1000 * 60 * 60 * 24));
      const finalLateFee = lateFeeAmount !== undefined ? Number(lateFeeAmount) : calculateAccruedLateFee(diffDays, sale.monthlyLateFee);
      const effectiveBaseAmount = Number(amount);

      sale.set(`paymentSchedule.${instIdx}.status`, 'Paid');
      sale.set(`paymentSchedule.${instIdx}.paidDate`, pDate);
      sale.set(`paymentSchedule.${instIdx}.paidAmount`, effectiveBaseAmount + finalLateFee);
      sale.set(`paymentSchedule.${instIdx}.lateFee`, finalLateFee);
      sale.set(`paymentSchedule.${instIdx}.notes`, notes || '');
      sale.set(`paymentSchedule.${instIdx}.method`, method || 'Cash');
      sale.set(`paymentSchedule.${instIdx}.voucherNumber`, voucherNumber || '');

      await applySaleRecalculations(sale, session);

      await syncInstallmentTransactions({
        sale,
        installmentNumber: Number(installmentNumber),
        baseAmount: effectiveBaseAmount,
        lateFee: finalLateFee,
        paymentDate: pDate,
        userId: user.userId,
        isReverted: false,
        session,
      });

      await logActivity({
        userId: user.userId,
        userName: user.name,
        action: `Recorded payment for installment ${installmentNumber} of sale ${sale.saleId} (Base: ${effectiveBaseAmount}, Fee: ${finalLateFee})`,
        module: 'Sales',
        targetId: sale._id.toString(),
        ipAddress: request.headers.get('x-forwarded-for') || 'unknown',
      });

      return sale;
    });

    return NextResponse.json({ sale: updatedSale });
  } catch (error: any) {
    console.error('Record payment error:', error);
    if (error instanceof DatabaseConnectionError) {
      return NextResponse.json({ error: error.message }, { status: error.statusCode });
    }
    return NextResponse.json({ error: error.message || 'Internal server error' }, { status: 400 });
  }
}

export async function PUT(
  request: NextRequest,
  { params }: { params: Promise<{ id: string }> }
) {
  try {
    await connectDB();
    const user = await getAuthPayload(request);
    if (!user) {
      return NextResponse.json({ error: 'Unauthorized' }, { status: 401 });
    }

    if (!user.normalizedRoles.some(r => ['Admin', 'Sales Person', 'Accountant', 'Finance Manager'].includes(r))) {
      return NextResponse.json({ error: 'Forbidden' }, { status: 403 });
    }

    const { id } = await params;
    if (!mongoose.Types.ObjectId.isValid(id)) {
      return NextResponse.json({ error: 'Invalid sale ID' }, { status: 400 });
    }

    const body = await request.json();
    const {
      installmentNumber,
      action = 'edit', // 'edit' | 'revert'
      amount,
      lateFeeAmount,
      paymentDate,
      dueDate,
      notes,
      method,
      voucherNumber,
    } = body;

    if (!installmentNumber) {
      return NextResponse.json({ error: 'Installment number is required' }, { status: 400 });
    }

    const updatedSale = await runInTransaction(async (session) => {
      const sale = await InstallmentSale.findById(id).session(session);
      if (!sale) {
        throw new Error('Sale not found');
      }

      const instIdx = sale.paymentSchedule.findIndex(p => p.installmentNumber === Number(installmentNumber));
      if (instIdx === -1) {
        throw new Error('Invalid installment number');
      }

      const inst = sale.paymentSchedule[instIdx];

      if (action === 'revert') {
        if (inst.status !== 'Paid') {
          throw new Error('Only paid installments can be reverted');
        }

        const isPastDue = new Date(inst.dueDate) < new Date();
        sale.set(`paymentSchedule.${instIdx}.status`, isPastDue ? 'Overdue' : 'Pending');
        sale.set(`paymentSchedule.${instIdx}.paidDate`, undefined);
        sale.set(`paymentSchedule.${instIdx}.paidAmount`, undefined);
        sale.set(`paymentSchedule.${instIdx}.lateFee`, 0);
        sale.set(`paymentSchedule.${instIdx}.method`, undefined);
        sale.set(`paymentSchedule.${instIdx}.voucherNumber`, undefined);
        if (notes !== undefined) {
          sale.set(`paymentSchedule.${instIdx}.notes`, notes);
        }

        await applySaleRecalculations(sale, session);

        await syncInstallmentTransactions({
          sale,
          installmentNumber: Number(installmentNumber),
          isReverted: true,
          userId: user.userId,
          session,
        });

        await logActivity({
          userId: user.userId,
          userName: user.name,
          action: `Reverted payment for installment #${installmentNumber} of sale ${sale.saleId}`,
          module: 'Sales',
          targetId: sale._id.toString(),
          ipAddress: request.headers.get('x-forwarded-for') || 'unknown',
        });

        return sale;
      }

      // Action: 'edit'
      if (inst.status === 'Paid') {
        const effectiveBaseAmount = amount !== undefined ? Number(amount) : (Number(inst.paidAmount || inst.amount) - Number(inst.lateFee || 0));
        const effectiveLateFee = lateFeeAmount !== undefined ? Number(lateFeeAmount) : Number(inst.lateFee || 0);
        const effectivePaidDate = paymentDate ? new Date(paymentDate) : (inst.paidDate ? new Date(inst.paidDate) : new Date());

        sale.set(`paymentSchedule.${instIdx}.paidDate`, effectivePaidDate);
        sale.set(`paymentSchedule.${instIdx}.paidAmount`, effectiveBaseAmount + effectiveLateFee);
        sale.set(`paymentSchedule.${instIdx}.lateFee`, effectiveLateFee);
        if (amount !== undefined) {
          sale.set(`paymentSchedule.${instIdx}.amount`, effectiveBaseAmount);
        }
        if (dueDate) {
          sale.set(`paymentSchedule.${instIdx}.dueDate`, new Date(dueDate));
        }
        if (method !== undefined) {
          sale.set(`paymentSchedule.${instIdx}.method`, method);
        }
        if (voucherNumber !== undefined) {
          sale.set(`paymentSchedule.${instIdx}.voucherNumber`, voucherNumber);
        }
        if (notes !== undefined) {
          sale.set(`paymentSchedule.${instIdx}.notes`, notes);
        }

        await applySaleRecalculations(sale, session);

        await syncInstallmentTransactions({
          sale,
          installmentNumber: Number(installmentNumber),
          baseAmount: effectiveBaseAmount,
          lateFee: effectiveLateFee,
          paymentDate: effectivePaidDate,
          userId: user.userId,
          isReverted: false,
          session,
        });

        await logActivity({
          userId: user.userId,
          userName: user.name,
          action: `Edited paid installment #${installmentNumber} of sale ${sale.saleId} (Base: ${effectiveBaseAmount}, Fee: ${effectiveLateFee})`,
          module: 'Sales',
          targetId: sale._id.toString(),
          ipAddress: request.headers.get('x-forwarded-for') || 'unknown',
        });
      } else {
        // Editing an unpaid installment schedule item
        if (amount !== undefined) {
          sale.set(`paymentSchedule.${instIdx}.amount`, Number(amount));
        }
        if (dueDate) {
          const newDueDate = new Date(dueDate);
          sale.set(`paymentSchedule.${instIdx}.dueDate`, newDueDate);
          sale.set(`paymentSchedule.${instIdx}.status`, newDueDate < new Date() ? 'Overdue' : 'Pending');
        }
        if (notes !== undefined) {
          sale.set(`paymentSchedule.${instIdx}.notes`, notes);
        }

        await applySaleRecalculations(sale, session);

        await logActivity({
          userId: user.userId,
          userName: user.name,
          action: `Edited scheduled installment #${installmentNumber} of sale ${sale.saleId}`,
          module: 'Sales',
          targetId: sale._id.toString(),
          ipAddress: request.headers.get('x-forwarded-for') || 'unknown',
        });
      }

      return sale;
    });

    return NextResponse.json({ sale: updatedSale });
  } catch (error: any) {
    console.error('Update installment error:', error);
    if (error instanceof DatabaseConnectionError) {
      return NextResponse.json({ error: error.message }, { status: error.statusCode });
    }
    return NextResponse.json({ error: error.message || 'Internal server error' }, { status: 400 });
  }
}

export async function DELETE(
  request: NextRequest,
  { params }: { params: Promise<{ id: string }> }
) {
  try {
    await connectDB();
    const user = await getAuthPayload(request);
    if (!user) {
      return NextResponse.json({ error: 'Unauthorized' }, { status: 401 });
    }

    if (!user.normalizedRoles.some(r => ['Admin', 'Accountant', 'Finance Manager'].includes(r))) {
      return NextResponse.json({ error: 'Forbidden' }, { status: 403 });
    }

    const { id } = await params;
    if (!mongoose.Types.ObjectId.isValid(id)) {
      return NextResponse.json({ error: 'Invalid sale ID' }, { status: 400 });
    }

    const { searchParams } = new URL(request.url);
    const installmentNumber = parseInt(searchParams.get('installmentNumber') || '');

    if (!installmentNumber) {
      return NextResponse.json({ error: 'Installment number is required' }, { status: 400 });
    }

    const updatedSale = await runInTransaction(async (session) => {
      const sale = await InstallmentSale.findById(id).session(session);
      if (!sale) {
        throw new Error('Sale not found');
      }

      const instIdx = sale.paymentSchedule.findIndex(p => p.installmentNumber === installmentNumber);
      if (instIdx === -1) {
        throw new Error('Invalid installment number');
      }

      const inst = sale.paymentSchedule[instIdx];
      if (inst.status !== 'Paid') {
        throw new Error('Only paid installments can be reverted');
      }

      const isPastDue = new Date(inst.dueDate) < new Date();
      sale.set(`paymentSchedule.${instIdx}.status`, isPastDue ? 'Overdue' : 'Pending');
      sale.set(`paymentSchedule.${instIdx}.paidDate`, undefined);
      sale.set(`paymentSchedule.${instIdx}.paidAmount`, undefined);
      sale.set(`paymentSchedule.${instIdx}.lateFee`, 0);
      sale.set(`paymentSchedule.${instIdx}.method`, undefined);
      sale.set(`paymentSchedule.${instIdx}.voucherNumber`, undefined);

      await applySaleRecalculations(sale, session);

      await syncInstallmentTransactions({
        sale,
        installmentNumber,
        isReverted: true,
        userId: user.userId,
        session,
      });

      await logActivity({
        userId: user.userId,
        userName: user.name,
        action: `Reverted payment for installment #${installmentNumber} of sale ${sale.saleId}`,
        module: 'Sales',
        targetId: sale._id.toString(),
        ipAddress: request.headers.get('x-forwarded-for') || 'unknown',
      });

      return sale;
    });

    return NextResponse.json({ sale: updatedSale });
  } catch (error: any) {
    console.error('Delete installment payment error:', error);
    if (error instanceof DatabaseConnectionError) {
      return NextResponse.json({ error: error.message }, { status: error.statusCode });
    }
    return NextResponse.json({ error: error.message || 'Internal server error' }, { status: 400 });
  }
}

