import { NextRequest, NextResponse } from 'next/server';
import { connectDB, DatabaseConnectionError, runInTransaction } from '@/lib/db';
import InstallmentSale from '@/models/InstallmentSale';
import Transaction from '@/models/Transaction';
import Car from '@/models/Car';
import { getAuthPayload } from '@/lib/apiAuth';
import { logActivity } from '@/lib/activityLogger';
import { calculateAccruedLateFee } from '@/lib/installmentUtils';
import mongoose from 'mongoose';

export async function POST(
  request: NextRequest,
  { params }: { params: Promise<{ id: string }> }
) {
  try {
    await connectDB();
    const user = await getAuthPayload(request);
    if (!user) {
      return NextResponse.json({ error: 'Unauthorized' }, { status: 401 });
    }

    if (!user.normalizedRoles.some(r => ['Admin', 'Sales Person', 'Accountant', 'Finance Manager'].includes(r))) {
      return NextResponse.json({ error: 'Forbidden' }, { status: 403 });
    }

    const { id } = await params;

    if (!mongoose.Types.ObjectId.isValid(id)) {
      return NextResponse.json({ error: 'Invalid sale ID' }, { status: 400 });
    }

    const body = await request.json();
    const { installmentNumber, amount, lateFeeAmount, paymentDate, notes, method, voucherNumber } = body;

    if (!installmentNumber || amount === undefined || !paymentDate) {
      return NextResponse.json({ error: 'Installment number, amount and payment date are required' }, { status: 400 });
    }

    const updatedSale = await runInTransaction(async (session) => {
      // Find sale first to validate installment exists and state
      const sale = await InstallmentSale.findById(id).session(session);
      if (!sale) {
        throw new Error('Sale not found');
      }

      const inst = sale.paymentSchedule.find(p => p.installmentNumber === installmentNumber);
      if (!inst) {
        throw new Error('Invalid installment number');
      }
      if (inst.status === 'Paid') {
        throw new Error('Installment already paid');
      }

      // Calculate late fee: 10 day grace period, then flat fee per month
      const dueDate = new Date(inst.dueDate);
      const pDate = new Date(paymentDate);
      const diffTime = pDate.getTime() - dueDate.getTime();
      const diffDays = Math.floor(diffTime / (1000 * 60 * 60 * 24));
      
      const finalLateFee = lateFeeAmount !== undefined ? Number(lateFeeAmount) : calculateAccruedLateFee(diffDays, sale.monthlyLateFee);

      // Atomic update of the installment and totals
      const us = await InstallmentSale.findByIdAndUpdate(
        id,
        {
          $set: {
            'paymentSchedule.$[elem].status': 'Paid',
            'paymentSchedule.$[elem].paidDate': new Date(paymentDate),
            'paymentSchedule.$[elem].paidAmount': amount + finalLateFee,
            'paymentSchedule.$[elem].lateFee': finalLateFee,
            'paymentSchedule.$[elem].notes': notes,
            'paymentSchedule.$[elem].method': method || 'Cash',
            'paymentSchedule.$[elem].voucherNumber': voucherNumber,
          },
          $inc: {
            totalPaid: amount + finalLateFee,
            remainingAmount: -amount, // Only decrement remaining balance by the base amount
            lateFeeCharged: finalLateFee
          }
        },
        {
          session,
          new: true,
          arrayFilters: [{ 'elem.installmentNumber': installmentNumber }]
        }
      );

      if (!us) {
        throw new Error('Failed to update sale');
      }

      // Recalculate next payment info based on new state
      const schedule = us.paymentSchedule || [];
      const nextUnpaid = schedule.find(p => p.status !== 'Paid');

      if (nextUnpaid) {
        us.nextPaymentDate = nextUnpaid.dueDate;
        us.nextPaymentAmount = nextUnpaid.amount;

        // Check if there are any remaining overdue installments
        const hasOverdue = schedule.some(p => p.status === 'Overdue');
        if (!hasOverdue && us.status === 'Defaulted') {
          us.status = 'Active';
          await Car.findByIdAndUpdate(us.car, { status: 'On Installment' }, { session });
        } else if (hasOverdue) {
          us.status = 'Defaulted';
          await Car.findByIdAndUpdate(us.car, { status: 'Defaulted' }, { session });
        }
      } else {
        us.status = 'Completed';
        us.nextPaymentDate = null as unknown as Date;
        us.nextPaymentAmount = 0;
        await Car.findByIdAndUpdate(us.car, { status: 'Sold' }, { session });
      }
      await us.save({ session });

      // Create ledger transactions
      const transactions: any[] = [{
        date: new Date(paymentDate),
        type: 'Income',
        category: 'Installment Payment',
        amount: amount,
        description: `Installment #${installmentNumber} base payment for ${us.saleId} - Car ${us.carId}`,
        referenceId: us._id.toString(),
        referenceType: 'InstallmentSale',
        isAutoGenerated: true,
        createdBy: user.userId,
      }];

      if (finalLateFee > 0) {
        transactions.push({
          date: new Date(paymentDate),
          type: 'Income',
          category: 'Fee', // Or 'Installment Payment'
          amount: finalLateFee,
          description: `Late fee collected for installment #${installmentNumber} - Sale ${us.saleId}`,
          referenceId: us._id.toString(),
          referenceType: 'InstallmentSale',
          isAutoGenerated: true,
          createdBy: user.userId,
        });
      }

      // Create ledger transactions sequentially to ensure the pre-save hook 
      // generates unique sequential transaction IDs
      for (const txData of transactions) {
        await Transaction.create([txData], { session });
      }

      await logActivity({
        userId: user.userId,
        userName: user.name,
        action: `Recorded payment for installment ${installmentNumber} of sale ${us.saleId} (Base: ${amount}, Fee: ${finalLateFee})`,
        module: 'Sales',
        targetId: us._id.toString(),
        ipAddress: request.headers.get('x-forwarded-for') || 'unknown',
      });

      return us;
    });

    return NextResponse.json({ sale: updatedSale });
  } catch (error: any) {
    console.error('Record payment error:', error);
    if (error instanceof DatabaseConnectionError) {
      return NextResponse.json({ error: error.message }, { status: error.statusCode });
    }
    return NextResponse.json({ error: error.message || 'Internal server error' }, { status: 400 });
  }
}
