import { NextRequest, NextResponse } from 'next/server';
import { connectDB, DatabaseConnectionError } from '@/lib/db';
import InstallmentSale from '@/models/InstallmentSale';
import Car from '@/models/Car';
import Customer from '@/models/Customer';
import Transaction from '@/models/Transaction';
import { getAuthPayload } from '@/lib/apiAuth';
import { logActivity } from '@/lib/activityLogger';
import { processZatcaInvoice, calculateVat, ZATCA_VAT_RATE } from '@/lib/zatca/invoiceService';
import { getTafweedStatus, validateTafweedAuthorization } from '@/lib/tafweed';
import mongoose from 'mongoose';

export async function GET(
  request: NextRequest,
  { params }: { params: Promise<{ id: string }> }
) {
  try {
    const { id } = await params;
    const user = await getAuthPayload(request);
    if (!user) {
      return NextResponse.json({ error: 'Unauthorized' }, { status: 401 });
    }

    if (!['Admin', 'Sales Person'].includes(user.normalizedRole || '')) {
      return NextResponse.json({ error: 'Forbidden' }, { status: 403 });
    }

    await connectDB();

    const sale = await InstallmentSale.findById(id).lean();
    if (!sale) {
      return NextResponse.json({ error: 'Sale not found' }, { status: 404 });
    }

    return NextResponse.json({ sale });
  } catch (error) {
    console.error('Get installment sale error:', error);

    if (error instanceof DatabaseConnectionError) {
      return NextResponse.json({ error: error.message }, { status: error.statusCode });
    }

    return NextResponse.json({ error: 'Internal server error' }, { status: 500 });
  }
}

export async function PUT(
  request: NextRequest,
  { params }: { params: Promise<{ id: string }> }
) {
  try {
    const { id } = await params;
    const user = await getAuthPayload(request);
    if (!user) {
      return NextResponse.json({ error: 'Unauthorized' }, { status: 401 });
    }

    if (!['Admin', 'Sales Person'].includes(user.normalizedRole || '')) {
      return NextResponse.json({ error: 'Forbidden' }, { status: 403 });
    }

    await connectDB();

    if (!mongoose.Types.ObjectId.isValid(id)) {
      return NextResponse.json({ error: 'Invalid sale ID' }, { status: 400 });
    }

    const sale = await InstallmentSale.findById(id);
    if (!sale) {
      return NextResponse.json({ error: 'Sale not found' }, { status: 404 });
    }

    if (sale.status === 'Cancelled') {
      return NextResponse.json({ error: 'Cannot update cancelled sale' }, { status: 400 });
    }

    const body = await request.json();
    const {
      downPayment, monthlyPayment, interestRate, tenureMonths, notes, invoiceType, buyerTrn, agentName, agentCommission, status,
      tafweedAuthorizedTo, tafweedDriverIqama, tafweedExpiryDate, tafweedDurationMonths,
    } = body;

    if (status !== undefined && status === 'Cancelled') {
        sale.status = 'Cancelled';
        await Promise.all([
          sale.save(),
          Car.findByIdAndUpdate(sale.car, {
            status: 'In Stock',
            tafweedStatus: 'None',
            tafweedAuthorizedTo: '',
            tafweedDriverIqama: '',
            tafweedDurationMonths: null,
            tafweedExpiryDate: null,
          }),
        (await import('@/models/Transaction')).default.updateMany(
          { referenceId: sale._id.toString(), referenceType: 'InstallmentSale', isAutoGenerated: true },
          { isDeleted: true }
        ),
      ]);

      await logActivity({
        userId: user.userId,
        userName: user.name,
        action: `Cancelled installment sale: ${sale.saleId}`,
        module: 'Sales',
        targetId: sale._id.toString(),
        ipAddress: request.headers.get('x-forwarded-for') || 'unknown',
      });

      return NextResponse.json({ sale });
    }

    if (downPayment !== undefined) sale.downPayment = downPayment;
    if (monthlyPayment !== undefined) sale.monthlyPayment = monthlyPayment;
    if (interestRate !== undefined) sale.interestRate = interestRate;
    if (tenureMonths !== undefined) sale.tenureMonths = tenureMonths;
    if (notes !== undefined) sale.notes = notes;
    if (agentName !== undefined) (sale as any).agentName = agentName;
    if (agentCommission !== undefined) (sale as any).agentCommission = agentCommission;
    if (
      tafweedAuthorizedTo !== undefined ||
      tafweedDriverIqama !== undefined ||
      tafweedExpiryDate !== undefined ||
      tafweedDurationMonths !== undefined
    ) {
      let validated;
      try {
        validated = validateTafweedAuthorization({
          startDate: sale.startDate,
          customerName: sale.customerName,
          tafweedAuthorizedTo: tafweedAuthorizedTo ?? sale.tafweedAuthorizedTo,
          tafweedDriverIqama: tafweedDriverIqama ?? sale.tafweedDriverIqama,
          tafweedExpiryDate: tafweedExpiryDate ?? sale.tafweedExpiryDate,
          tafweedDurationMonths: tafweedDurationMonths ?? sale.tafweedDurationMonths,
          allowExpired: true,
        });
      } catch (validationError) {
        return NextResponse.json(
          { error: validationError instanceof Error ? validationError.message : 'Invalid Tafweed details' },
          { status: 400 }
        );
      }

      sale.tafweedAuthorizedTo = validated.authorizedTo;
      sale.tafweedDriverIqama = validated.driverIqama;
      sale.tafweedDurationMonths = validated.durationMonths;
      sale.tafweedExpiryDate = validated.expiryDate;
      (sale as any).tafweedStatus = getTafweedStatus(validated.expiryDate);
    }

    const zatcaFieldChanged = invoiceType !== undefined || buyerTrn !== undefined;
    if (invoiceType !== undefined) sale.invoiceType = invoiceType;
    if (buyerTrn !== undefined) (sale as any).buyerTrn = buyerTrn;

    await sale.save();

    // Sync Tafweed info to car if updated
    if (
      tafweedAuthorizedTo !== undefined ||
      tafweedDriverIqama !== undefined ||
      tafweedExpiryDate !== undefined ||
      tafweedDurationMonths !== undefined
    ) {
      await Car.findByIdAndUpdate(sale.car, {
        tafweedAuthorizedTo: sale.tafweedAuthorizedTo,
        tafweedDriverIqama: sale.tafweedDriverIqama,
        tafweedDurationMonths: sale.tafweedDurationMonths,
        tafweedExpiryDate: sale.tafweedExpiryDate,
        tafweedStatus: getTafweedStatus(sale.tafweedExpiryDate as Date | string | null),
      });
    }

    // Re-run ZATCA if invoiceType or buyerTrn changed
    if (zatcaFieldChanged) {
      try {
        const [customerDoc, carDoc] = await Promise.all([
          Customer.findById(sale.customer).lean(),
          Car.findById(sale.car).lean(),
        ]);
        const vatInfo = calculateVat(sale.totalPrice, ZATCA_VAT_RATE);
        const zatcaResult = await processZatcaInvoice({
          referenceId: sale._id.toString(),
          referenceType: 'InstallmentSale',
          saleId: sale.saleId,
          invoiceType: (sale.invoiceType as 'Standard' | 'Simplified') || 'Simplified',
          issueDate: new Date(sale.startDate),
          supplyDate: new Date(sale.startDate),
          buyer: {
            name: sale.customerName,
            trn: (sale as any).buyerTrn || '',
            buildingNumber: (customerDoc as any)?.buildingNumber,
            streetName: (customerDoc as any)?.streetName,
            district: (customerDoc as any)?.district,
            city: (customerDoc as any)?.city,
            postalCode: (customerDoc as any)?.postalCode,
            countryCode: (customerDoc as any)?.countryCode || 'SA',
            otherId: (customerDoc as any)?.otherId ? {
              id: (customerDoc as any).otherId,
              type: (customerDoc as any).otherIdType || 'CRN'
            } : undefined
          },
          lineItems: [{
            name: carDoc ? `${carDoc.brand} ${carDoc.model} (${sale.carId})`.trim() : sale.carId,
            quantity: 1,
            unitPrice: vatInfo.subtotal,
            vatRate: ZATCA_VAT_RATE,
            vatAmount: vatInfo.vatAmount,
            totalAmount: vatInfo.totalWithVat,
          }],
          subtotal: vatInfo.subtotal,
          vatTotal: vatInfo.vatAmount,
          totalWithVat: vatInfo.totalWithVat,
          notes: sale.notes,
          createdBy: user.userId,
        });
        await InstallmentSale.findByIdAndUpdate(sale._id, {
          zatcaUUID: zatcaResult.uuid,
          zatcaQRCode: zatcaResult.qrCode,
          zatcaHash: zatcaResult.xmlHash,
          zatcaStatus: zatcaResult.status,
          zatcaResponse: zatcaResult.zatcaResponse,
          vatAmount: vatInfo.vatAmount,
          finalPriceWithVat: vatInfo.totalWithVat,
        });
      } catch (zatcaError) {
        console.error('ZATCA reprocessing failed:', zatcaError);
      }
    }

    await logActivity({
      userId: user.userId,
      userName: user.name,
      action: `Updated installment sale: ${sale.saleId}`,
      module: 'Sales',
      targetId: sale._id.toString(),
      ipAddress: request.headers.get('x-forwarded-for') || 'unknown',
    });

    return NextResponse.json({ sale });
  } catch (error) {
    console.error('Update installment sale error:', error);

    if (error instanceof DatabaseConnectionError) {
      return NextResponse.json({ error: error.message }, { status: error.statusCode });
    }

    return NextResponse.json({ error: 'Internal server error' }, { status: 500 });
  }
}

export async function DELETE(
  request: NextRequest,
  { params }: { params: Promise<{ id: string }> }
) {
  try {
    const { id } = await params;
    const user = await getAuthPayload(request);
    if (!user) {
      return NextResponse.json({ error: 'Unauthorized' }, { status: 401 });
    }

    if (!['Admin', 'Sales Person'].includes(user.normalizedRole || '')) {
      return NextResponse.json({ error: 'Forbidden' }, { status: 403 });
    }

    await connectDB();

    if (!mongoose.Types.ObjectId.isValid(id)) {
      return NextResponse.json({ error: 'Invalid sale ID' }, { status: 400 });
    }

    const sale = await InstallmentSale.findById(id);
    if (!sale) {
      return NextResponse.json({ error: 'Sale not found' }, { status: 404 });
    }

    if (sale.status === 'Cancelled') {
      return NextResponse.json({ error: 'Sale already cancelled' }, { status: 400 });
    }

    // Soft delete
    await InstallmentSale.findByIdAndUpdate(id, { isDeleted: true });

    await Promise.all([
      Car.findByIdAndUpdate(sale.car, {
        status: 'In Stock',
        tafweedStatus: 'None',
        tafweedAuthorizedTo: '',
        tafweedDriverIqama: '',
        tafweedDurationMonths: null,
        tafweedExpiryDate: null,
      }),
      Transaction.updateMany(
        { referenceId: sale._id.toString(), referenceType: 'InstallmentSale', isAutoGenerated: true },
        { isDeleted: true }
      ),
    ]);

    await logActivity({
      userId: user.userId,
      userName: user.name,
      action: `Deleted installment sale: ${sale.saleId}`,
      module: 'Sales',
      targetId: id,
      ipAddress: request.headers.get('x-forwarded-for') || 'unknown',
    });

    return NextResponse.json({ message: 'Sale deleted successfully' });
  } catch (error) {
    console.error('Delete installment sale error:', error);

    if (error instanceof DatabaseConnectionError) {
      return NextResponse.json({ error: error.message }, { status: error.statusCode });
    }

    return NextResponse.json({ error: 'Internal server error' }, { status: 500 });
  }
}
