import { NextRequest, NextResponse } from 'next/server';
import { connectDB, DatabaseConnectionError } from '@/lib/db';
import InstallmentSale from '@/models/InstallmentSale';
import Car from '@/models/Car';
import Transaction from '@/models/Transaction';
import { getAuthPayload } from '@/lib/apiAuth';
import { logActivity } from '@/lib/activityLogger';
import mongoose from 'mongoose';

export async function GET(
  request: NextRequest,
  { params }: { params: Promise<{ id: string }> }
) {
  try {
    const { id } = await params;
    const user = await getAuthPayload(request);
    if (!user) {
      return NextResponse.json({ error: 'Unauthorized' }, { status: 401 });
    }

    await connectDB();

    const sale = await InstallmentSale.findById(id).lean();
    if (!sale) {
      return NextResponse.json({ error: 'Sale not found' }, { status: 404 });
    }

    return NextResponse.json({ sale });
  } catch (error) {
    console.error('Get installment sale error:', error);

    if (error instanceof DatabaseConnectionError) {
      return NextResponse.json({ error: error.message }, { status: error.statusCode });
    }

    return NextResponse.json({ error: 'Internal server error' }, { status: 500 });
  }
}

export async function PUT(
  request: NextRequest,
  { params }: { params: Promise<{ id: string }> }
) {
  try {
    const { id } = await params;
    const user = await getAuthPayload(request);
    if (!user) {
      return NextResponse.json({ error: 'Unauthorized' }, { status: 401 });
    }

    await connectDB();

    if (!mongoose.Types.ObjectId.isValid(id)) {
      return NextResponse.json({ error: 'Invalid sale ID' }, { status: 400 });
    }

    const sale = await InstallmentSale.findById(id);
    if (!sale) {
      return NextResponse.json({ error: 'Sale not found' }, { status: 404 });
    }

    if (sale.status === 'Cancelled') {
      return NextResponse.json({ error: 'Cannot update cancelled sale' }, { status: 400 });
    }

    const body = await request.json();
    const { downPayment, monthlyPayment, interestRate, tenureMonths, notes } = body;

    if (downPayment !== undefined) sale.downPayment = downPayment;
    if (monthlyPayment !== undefined) sale.monthlyPayment = monthlyPayment;
    if (interestRate !== undefined) sale.interestRate = interestRate;
    if (tenureMonths !== undefined) sale.tenureMonths = tenureMonths;
    if (notes !== undefined) sale.notes = notes;

    await sale.save();

    await logActivity({
      userId: user.userId,
      userName: user.name,
      action: `Updated installment sale: ${sale.saleId}`,
      module: 'Sales',
      targetId: sale._id.toString(),
      ipAddress: request.headers.get('x-forwarded-for') || 'unknown',
    });

    return NextResponse.json({ sale });
  } catch (error) {
    console.error('Update installment sale error:', error);

    if (error instanceof DatabaseConnectionError) {
      return NextResponse.json({ error: error.message }, { status: error.statusCode });
    }

    return NextResponse.json({ error: 'Internal server error' }, { status: 500 });
  }
}

export async function DELETE(
  request: NextRequest,
  { params }: { params: Promise<{ id: string }> }
) {
  try {
    const { id } = await params;
    const user = await getAuthPayload(request);
    if (!user) {
      return NextResponse.json({ error: 'Unauthorized' }, { status: 401 });
    }

    await connectDB();

    if (!mongoose.Types.ObjectId.isValid(id)) {
      return NextResponse.json({ error: 'Invalid sale ID' }, { status: 400 });
    }

    const sale = await InstallmentSale.findById(id);
    if (!sale) {
      return NextResponse.json({ error: 'Sale not found' }, { status: 404 });
    }

    if (sale.status === 'Cancelled') {
      return NextResponse.json({ error: 'Sale already cancelled' }, { status: 400 });
    }

    // Soft delete - mark as cancelled
    sale.status = 'Cancelled';
    await sale.save();

    // Update car back to available
    await Car.findByIdAndUpdate(sale.car, { status: 'In Stock' });

    // Soft delete related transactions
    await Transaction.updateMany(
      { referenceId: sale._id.toString(), referenceType: 'InstallmentSale', isAutoGenerated: true },
      { isDeleted: true }
    );

    await logActivity({
      userId: user.userId,
      userName: user.name,
      action: `Cancelled installment sale: ${sale.saleId}`,
      module: 'Sales',
      targetId: sale._id.toString(),
      ipAddress: request.headers.get('x-forwarded-for') || 'unknown',
    });

    return NextResponse.json({ message: 'Sale cancelled successfully' });
  } catch (error) {
    console.error('Delete installment sale error:', error);

    if (error instanceof DatabaseConnectionError) {
      return NextResponse.json({ error: error.message }, { status: error.statusCode });
    }

    return NextResponse.json({ error: 'Internal server error' }, { status: 500 });
  }
}