'use client';

import { useState, useEffect, useCallback } from 'react';
import Link from 'next/link';
import DataTransferButtons from '@/components/DataTransferButtons';
import { DateRangeFilter } from '@/components/DateRangeFilter';
import { useTranslations, useLocale } from 'next-intl';

interface Transaction {
  _id: string;
  transactionId: string;
  date: string;
  type: 'Income' | 'Expense';
  category: string;
  amount: number;
  description: string;
  isAutoGenerated: boolean;
}

interface Summary {
  income: number;
  expense: number;
  totalProfit: number;
  thisMonthIncome: number;
  thisMonthExpense: number;
  thisMonthProfit: number;
}

export default function FinancePage() {
  const t = useTranslations('Finance');
  const commonT = useTranslations('Common');
  const locale = useLocale();
  const isRtl = locale === 'ar';

  const [transactions, setTransactions] = useState<Transaction[]>([]);
  const [loading, setLoading] = useState(true);
  const [dateRange, setDateRange] = useState({ startDate: '', endDate: '' });
  const [typeFilter, setTypeFilter] = useState('');
  const [categoryFilter, setCategoryFilter] = useState('');
  const [page, setPage] = useState(1);
  const [totalPages, setTotalPages] = useState(1);
  const [summary, setSummary] = useState<Summary>({
    income: 0,
    expense: 0,
    totalProfit: 0,
    thisMonthIncome: 0,
    thisMonthExpense: 0,
    thisMonthProfit: 0,
  });
  const [showModal, setShowModal] = useState(false);
  const [editingTransaction, setEditingTransaction] = useState<Transaction | null>(null);
  const [selectedIds, setSelectedIds] = useState<Set<string>>(new Set());
  const [bulkActionLoading, setBulkActionLoading] = useState(false);

  const toggleSelectAll = () => {
    const manualTxns = transactions.filter(t => !t.isAutoGenerated);
    if (selectedIds.size === manualTxns.length && manualTxns.length > 0) {
      setSelectedIds(new Set());
    } else {
      setSelectedIds(new Set(manualTxns.map((t) => t._id)));
    }
  };

  const toggleSelect = (id: string) => {
    const next = new Set(selectedIds);
    if (next.has(id)) {
      next.delete(id);
    } else {
      next.add(id);
    }
    setSelectedIds(next);
  };

  const handleBulkDelete = async () => {
    if (!confirm(commonT('deleteConfirm'))) return;

    setBulkActionLoading(true);
    try {
      const res = await fetch('/api/transactions/bulk', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ action: 'delete', ids: Array.from(selectedIds) }),
      });

      if (res.ok) {
        const data = await res.json();
        if (data.deletedCount < selectedIds.size) {
          alert(`Deleted ${data.deletedCount} transactions. Some could not be deleted (auto-generated).`);
        }
        setSelectedIds(new Set());
        fetchTransactions();
      } else {
        const data = await res.json();
        alert(data.error || 'Bulk delete failed');
      }
    } catch (err) {
      console.error(err);
      alert('Network error');
    } finally {
      setBulkActionLoading(false);
    }
  };

  const fetchTransactions = useCallback(async () => {
    setLoading(true);
    const params = new URLSearchParams({ page: page.toString(), limit: '30' });
    if (typeFilter) params.set('type', typeFilter);
    if (categoryFilter) params.set('category', categoryFilter);
    if (dateRange.startDate) params.set('startDate', dateRange.startDate);
    if (dateRange.endDate) params.set('endDate', dateRange.endDate);

    try {
      const res = await fetch(`/api/transactions?${params}`);
      const data = await res.json();
      setTransactions(data.transactions || []);
      setTotalPages(data.pagination?.pages || 1);
      setSummary(data.summary || {
        income: 0,
        expense: 0,
        totalProfit: 0,
        thisMonthIncome: 0,
        thisMonthExpense: 0,
        thisMonthProfit: 0,
      });
    } catch (err) {
      console.error(err);
    } finally {
      setLoading(false);
    }
  }, [page, typeFilter, categoryFilter, dateRange]);

  useEffect(() => {
    fetchTransactions();
  }, [fetchTransactions]);

  useEffect(() => {
    setPage(1);
  }, [dateRange]);

  const categories = [
    'Car Purchase', 'Car Repair', 'Salary Payment', 'Office Expense', 
    'Cash Sale', 'Installment Payment', 'Rental Income', 'Other Income', 'Other Expense'
  ];

  const getCategoryLabel = (cat: string) => {
    const key = cat.replace(' ', '').charAt(0).toLowerCase() + cat.replace(' ', '').slice(1);
    return t(`categories.${key}`);
  };

  const formatCurrency = (val: number | undefined | null) => {
    const amount = val || 0;
    return `SAR ${amount.toLocaleString(locale === 'ar' ? 'ar-SA' : 'en-US')}`;
  };
  const profitMargin = summary.thisMonthIncome > 0
    ? ((summary.thisMonthProfit / summary.thisMonthIncome) * 100).toFixed(1)
    : '0';

  const handleEdit = (transaction: Transaction) => {
    if (transaction.isAutoGenerated) {
      alert('Cannot edit auto-generated transactions');
      return;
    }
    setEditingTransaction(transaction);
  };

  const handlePrint = () => window.print();

  const handleExportCSV = async () => {
    try {
      let exportData = [];
      if (selectedIds.size > 0) {
        exportData = transactions.filter(t => selectedIds.has(t._id));
      } else {
        const params = new URLSearchParams({ limit: '999999' });
        if (typeFilter) params.set('type', typeFilter);
        if (categoryFilter) params.set('category', categoryFilter);
        if (dateRange.startDate && dateRange.startDate !== 'undefined') params.set('startDate', dateRange.startDate);
        if (dateRange.endDate && dateRange.endDate !== 'undefined') params.set('endDate', dateRange.endDate);
        
        const res = await fetch(`/api/transactions?${params}`);
        const data = await res.json();
        exportData = data.transactions || [];
      }

      const csvHeader = ['Date,Type,Category,Description,Amount'];
      const csvRows = exportData.map((txn: any) => {
        const typeStr = txn.type === 'Income' ? t('income') : t('expense');
        const categoryStr = getCategoryLabel(txn.category);
        const dateStr = new Date(txn.date).toLocaleDateString(locale === 'ar' ? 'ar-SA' : 'en-US');
        const amountStr = `${txn.type === 'Income' ? '+' : '-'}${txn.amount}`;
        return `${dateStr},${typeStr},"${categoryStr}","${txn.description.replace(/"/g, '""')}",${amountStr}`;
      });
      
      const csvContent = '\uFEFF' + [csvHeader, ...csvRows].join('\n');
      const blob = new Blob([csvContent], { type: 'text/csv;charset=utf-8;' });
      const url = URL.createObjectURL(blob);
      const a = document.createElement('a');
      a.href = url;
      a.download = `transactions-${new Date().toISOString().split('T')[0]}.csv`;
      a.click();
      URL.revokeObjectURL(url);
    } catch (err) {
      console.error('Export failed:', err);
      alert('Export failed');
    }
  };

  const handleDelete = async (id: string) => {
    if (!confirm(t('deleteConfirm'))) return;
    try {
      const res = await fetch(`/api/transactions/${id}`, { method: 'DELETE' });
      if (!res.ok) { const data = await res.json(); alert(data.error || 'Failed'); return; }
      fetchTransactions();
    } catch (err) { console.error(err); }
  };

  const handleUpdateTransaction = async (id: string, data: any) => {
    try {
      const res = await fetch(`/api/transactions/${id}`, {
        method: 'PUT',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify(data),
      });
      const resData = await res.json();
      if (!res.ok) { alert(resData.error || 'Failed'); return; }
      
      if (resData.isPending) {
        alert(resData.message || 'Edit request submitted for admin approval');
      }
      
      setEditingTransaction(null);
      fetchTransactions();
    } catch (err) { console.error(err); }
  };

  return (
    <div style={{ marginBottom: '24px' }}>
      <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between', marginBottom: '24px', flexDirection: isRtl ? 'row-reverse' : 'row' }}>
        <h2 className="page-title">{t('transactions')}</h2>
        <div style={{ display: 'flex', gap: '8px', alignItems: 'center', flexDirection: isRtl ? 'row-reverse' : 'row' }}>
          <button onClick={handlePrint} style={{ background: '#5b6be7', color: '#fff', padding: '8px 16px', borderRadius: '3px', border: 'none', cursor: 'pointer', fontSize: '14px' }}>{commonT('export.print') || 'Print'}</button>
          <button onClick={handleExportCSV} style={{ background: '#42ca7f', color: '#fff', padding: '8px 16px', borderRadius: '3px', border: 'none', cursor: 'pointer', fontSize: '14px' }}>{commonT('export.csv') || 'Export CSV'}</button>
          <DataTransferButtons entityType="transactions" onImportSuccess={fetchTransactions} showExport={false} />
          <Link href="/dashboard/finance/reports" style={{ background: '#f5a623', color: '#fff', padding: '8px 16px', borderRadius: '3px', textDecoration: 'none', fontSize: '14px', fontWeight: 500 }}>{t('reports')}</Link>
          <Link href="/dashboard/finance/expenses" style={{ background: '#ec4561', color: '#fff', padding: '8px 16px', borderRadius: '3px', textDecoration: 'none', fontSize: '14px', fontWeight: 500 }}>{t('expenses')}</Link>
          <Link href="/dashboard/finance/incomes" style={{ background: '#42ca7f', color: '#fff', padding: '8px 16px', borderRadius: '3px', textDecoration: 'none', fontSize: '14px', fontWeight: 500 }}>{t('incomes')}</Link>
        </div>
      </div>

      <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(200px, 1fr))', gap: '16px', marginBottom: '24px' }}>
        <div className="card" style={{ padding: '20px', borderLeft: isRtl ? 'none' : '4px solid #42ca7f', borderRight: isRtl ? '4px solid #42ca7f' : 'none', textAlign: isRtl ? 'right' : 'left' }}>
          <p style={{ fontSize: '12px', color: '#9ca8b3', textTransform: 'uppercase' }}>{t('incomeThisMonth')}</p>
          <p style={{ fontSize: '24px', fontWeight: 700, color: '#42ca7f', margin: '4px 0 0' }}>{formatCurrency(summary.thisMonthIncome)}</p>
        </div>
        <div className="card" style={{ padding: '20px', borderLeft: isRtl ? 'none' : '4px solid #ec4561', borderRight: isRtl ? '4px solid #ec4561' : 'none', textAlign: isRtl ? 'right' : 'left' }}>
          <p style={{ fontSize: '12px', color: '#9ca8b3', textTransform: 'uppercase' }}>{t('expensesThisMonth')}</p>
          <p style={{ fontSize: '24px', fontWeight: 700, color: '#ec4561', margin: '4px 0 0' }}>{formatCurrency(summary.thisMonthExpense)}</p>
        </div>
        <div className="card" style={{ padding: '20px', borderLeft: isRtl ? 'none' : '4px solid #28aaa9', borderRight: isRtl ? '4px solid #28aaa9' : 'none', textAlign: isRtl ? 'right' : 'left' }}>
          <p style={{ fontSize: '12px', color: '#9ca8b3', textTransform: 'uppercase' }}>{t('netProfit')}</p>
          <p style={{ fontSize: '24px', fontWeight: 700, color: '#28aaa9', margin: '4px 0 0' }}>{formatCurrency(summary.thisMonthProfit)}</p>
        </div>
        <div className="card" style={{ padding: '20px', borderLeft: isRtl ? 'none' : '4px solid #f5a623', borderRight: isRtl ? '4px solid #f5a623' : 'none', textAlign: isRtl ? 'right' : 'left' }}>
          <p style={{ fontSize: '12px', color: '#9ca8b3', textTransform: 'uppercase' }}>{t('profitMargin')}</p>
          <p style={{ fontSize: '24px', fontWeight: 700, color: '#f5a623', margin: '4px 0 0' }}>{profitMargin}%</p>
        </div>
      </div>

      <div className="no-print" style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between', marginBottom: '24px', flexDirection: isRtl ? 'row-reverse' : 'row' }}>
        <div style={{ display: 'flex', gap: '12px', alignItems: 'center', flexWrap: 'wrap', flexDirection: isRtl ? 'row-reverse' : 'row' }}>
          <select value={typeFilter} onChange={(e) => { setTypeFilter(e.target.value); setPage(1); }} style={{ height: '40px', fontSize: '14px', borderRadius: '0', padding: '0 12px', border: '1px solid #ced4da', textAlign: isRtl ? 'right' : 'left' }}>
            <option value="">{t('allTypes')}</option>
            <option value="Income">{t('income')}</option>
            <option value="Expense">{t('expense')}</option>
          </select>
          <select value={categoryFilter} onChange={(e) => { setCategoryFilter(e.target.value); setPage(1); }} style={{ height: '40px', fontSize: '14px', borderRadius: '0', padding: '0 12px', border: '1px solid #ced4da', textAlign: isRtl ? 'right' : 'left' }}>
            <option value="">{t('allCategories')}</option>
            {categories.map(c => <option key={c} value={c}>{getCategoryLabel(c)}</option>)}
          </select>
          <div style={{ marginTop: '16px' }}>
            <DateRangeFilter initialPreset="all" onChange={(start, end) => setDateRange({ startDate: start, endDate: end })} />
          </div>
        </div>
        <button onClick={() => setShowModal(true)} style={{ background: '#28aaa9', color: '#ffffff', fontSize: '14px', fontWeight: 500, padding: '10px 16px', borderRadius: '3px', border: '1px solid #28aaa9', cursor: 'pointer' }}>+ {t('addTransaction')}</button>
      </div>

      {selectedIds.size > 0 && (
        <div className="no-print"
          style={{
            position: 'sticky',
            top: '0',
            zIndex: 10,
            background: '#ffffff',
            padding: '12px 16px',
            marginBottom: '16px',
            border: '1px solid #28aaa9',
            borderRadius: '4px',
            display: 'flex',
            alignItems: 'center',
            justifyContent: 'space-between',
            boxShadow: '0 2px 8px rgba(0,0,0,0.05)',
            flexDirection: isRtl ? 'row-reverse' : 'row'
          }}
        >
          <div style={{ display: 'flex', alignItems: 'center', gap: '12px', flexDirection: isRtl ? 'row-reverse' : 'row' }}>
            <span style={{ fontWeight: 600, color: '#28aaa9' }}>{selectedIds.size} {commonT('selected')}</span>
            <button
              onClick={handleBulkDelete}
              disabled={bulkActionLoading}
              style={{
                height: '32px',
                padding: '0 12px',
                fontSize: '13px',
                borderRadius: '3px',
                border: '1px solid #dc3545',
                background: '#ffffff',
                color: '#dc3545',
                cursor: 'pointer'
              }}
            >
              {commonT('deleteSelected')}
            </button>
          </div>
          <button
            onClick={() => setSelectedIds(new Set())}
            style={{
              background: 'none',
              border: 'none',
              color: '#9ca8b3',
              cursor: 'pointer',
              fontSize: '13px'
            }}
          >
            {commonT('cancel')}
          </button>
        </div>
      )}

      <div className="card" style={{ padding: 0, overflow: 'hidden' }}>
        {loading ? (
          <div style={{ padding: '32px', textAlign: 'center', color: '#9ca8b3' }}>{commonT('loading')}</div>
        ) : transactions.length === 0 ? (
          <div style={{ padding: '32px', textAlign: 'center', color: '#9ca8b3' }}>{t('noTransactions')}</div>
        ) : (
          <div style={{ overflowX: 'auto' }}>
            <table style={{ width: '100%', fontSize: '14px', minWidth: '800px', direction: isRtl ? 'rtl' : 'ltr' }}>
              <thead style={{ background: '#f8f9fa', borderBottom: '1px solid #eee' }}>
                <tr>
                  <th className="no-print" style={{ padding: '12px', width: '40px', textAlign: 'center' }}>
                    <input
                      type="checkbox"
                      checked={transactions.length > 0 && transactions.every(t => t.isAutoGenerated || selectedIds.has(t._id))}
                      ref={(input) => {
                        if (input) {
                          const manualTxns = transactions.filter(t => !t.isAutoGenerated);
                          input.indeterminate = selectedIds.size > 0 && selectedIds.size < manualTxns.length;
                        }
                      }}
                      onChange={toggleSelectAll}
                    />
                  </th>
                  <th style={{ padding: '12px', textAlign: isRtl ? 'right' : 'left', fontSize: '12px', fontWeight: 600, color: '#525f80', textTransform: 'uppercase' }}>{t('date')}</th>
                  <th style={{ padding: '12px', textAlign: isRtl ? 'right' : 'left', fontSize: '12px', fontWeight: 600, color: '#525f80', textTransform: 'uppercase' }}>{t('type')}</th>
                  <th style={{ padding: '12px', textAlign: isRtl ? 'right' : 'left', fontSize: '12px', fontWeight: 600, color: '#525f80', textTransform: 'uppercase' }}>{t('category')}</th>
                  <th style={{ padding: '12px', textAlign: isRtl ? 'right' : 'left', fontSize: '12px', fontWeight: 600, color: '#525f80', textTransform: 'uppercase' }}>{t('description')}</th>
                  <th style={{ padding: '12px', textAlign: isRtl ? 'left' : 'right', fontSize: '12px', fontWeight: 600, color: '#525f80', textTransform: 'uppercase' }}>{t('amount')}</th>
                  <th className="no-print" style={{ padding: '12px', textAlign: isRtl ? 'right' : 'left', fontSize: '12px', fontWeight: 600, color: '#525f80', textTransform: 'uppercase' }}>{commonT('actions')}</th>
                </tr>
              </thead>
              <tbody style={{ borderBottom: '1px solid #eee' }}>
                {transactions.map((txn) => (
                  <tr key={txn._id} style={{ borderBottom: '1px solid #f5f5f5', background: selectedIds.has(txn._id) ? '#28aaa905' : 'transparent' }}>
                    <td className="no-print" style={{ padding: '12px', textAlign: 'center' }}>
                      {!txn.isAutoGenerated && (
                        <input
                          type="checkbox"
                          checked={selectedIds.has(txn._id)}
                          onChange={() => toggleSelect(txn._id)}
                        />
                      )}
                    </td>
                    <td style={{ padding: '12px', color: '#525f80' }}>{new Date(txn.date).toLocaleDateString(locale === 'ar' ? 'ar-SA' : 'en-US')}</td>
                    <td style={{ padding: '12px' }}>
                      <span style={{ padding: '4px 8px', borderRadius: '3px', fontSize: '12px', fontWeight: 500, background: txn.type === 'Income' ? '#42ca7f20' : '#ec456120', color: txn.type === 'Income' ? '#42ca7f' : '#ec4561' }}>{txn.type === 'Income' ? t('income') : t('expense')}</span>
                    </td>
                    <td style={{ padding: '12px' }}>{getCategoryLabel(txn.category)}</td>
                    <td style={{ padding: '12px' }}>{txn.description}</td>
                    <td style={{ padding: '12px', fontWeight: 600, color: txn.type === 'Income' ? '#42ca7f' : '#ec4561', textAlign: isRtl ? 'left' : 'right' }}>{txn.type === 'Income' ? '+' : '-'}{formatCurrency(txn.amount)}</td>
                    <td className="no-print" style={{ padding: '12px' }}>
                      <div style={{ display: 'flex', gap: '8px', flexDirection: isRtl ? 'row-reverse' : 'row' }}>
                        {!txn.isAutoGenerated && (
                          <>
                            <button onClick={() => handleEdit(txn)} style={{ color: '#f8b425', background: 'none', border: 'none', cursor: 'pointer', padding: 0, fontSize: '14px' }}>{commonT('edit')}</button>
                            <button onClick={() => handleDelete(txn._id)} style={{ color: '#ec4561', background: 'none', border: 'none', cursor: 'pointer', padding: 0, fontSize: '14px' }}>{commonT('delete')}</button>
                          </>
                        )}
                        {txn.isAutoGenerated && <span style={{ fontSize: '12px', color: '#9ca8b3' }}>{t('auto')}</span>}
                      </div>
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        )}
      </div>

      {totalPages > 1 && (
        <div className="no-print" style={{ display: 'flex', gap: '8px', justifyContent: 'flex-end', marginTop: '16px', flexDirection: isRtl ? 'row-reverse' : 'row' }}>
          <button onClick={() => setPage((p) => Math.max(1, p - 1))} disabled={page === 1} style={{ padding: '8px 12px', fontSize: '12px', border: '1px solid #ced4da', borderRadius: '3px', background: '#ffffff', cursor: page === 1 ? 'not-allowed' : 'pointer', opacity: page === 1 ? 0.5 : 1 }}>{commonT('prev')}</button>
          <span style={{ padding: '8px 12px', fontSize: '12px', color: '#525f80' }}>{commonT('page', { page, total: totalPages })}</span>
          <button onClick={() => setPage((p) => Math.min(totalPages, p + 1))} disabled={page === totalPages} style={{ padding: '8px 12px', fontSize: '12px', border: '1px solid #ced4da', borderRadius: '3px', background: '#ffffff', cursor: page === totalPages ? 'not-allowed' : 'pointer', opacity: page === totalPages ? 0.5 : 1 }}>{commonT('next')}</button>
        </div>
      )}

      {showModal && <TransactionModal onClose={() => setShowModal(false)} onSave={() => { setShowModal(false); fetchTransactions(); }} />}
      {editingTransaction && <EditTransactionModal transaction={editingTransaction} onClose={() => setEditingTransaction(null)} onSave={handleUpdateTransaction} />}
    </div>
  );
}

function TransactionModal({ onClose, onSave }: { onClose: () => void; onSave: () => void }) {
  const t = useTranslations('Finance');
  const commonT = useTranslations('Common');
  const locale = useLocale();
  const isRtl = locale === 'ar';

  const [form, setForm] = useState({ date: new Date().toISOString().split('T')[0], type: 'Income', category: 'Other Income', amount: '', description: '' });
  const [loading, setLoading] = useState(false);

  const incomeCategories = ['Cash Sale', 'Installment Payment', 'Rental Income', 'Other Income'];
  const expenseCategories = ['Car Purchase', 'Car Repair', 'Salary Payment', 'Office Expense', 'Other Expense'];
  const categories = form.type === 'Income' ? incomeCategories : expenseCategories;

  const getCategoryLabel = (cat: string) => {
    const key = cat.replace(' ', '').charAt(0).toLowerCase() + cat.replace(' ', '').slice(1);
    return t(`categories.${key}`);
  };

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    setLoading(true);
    try {
      const res = await fetch('/api/transactions', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(form) });
      if (!res.ok) { const data = await res.json(); alert(data.error || 'Failed'); return; }
      onSave();
    } catch (err) { console.error(err); } finally { setLoading(false); }
  };

  return (
    <div style={{ position: 'fixed', top: 0, left: 0, right: 0, bottom: 0, background: 'rgba(0,0,0,0.5)', display: 'flex', alignItems: 'center', justifyContent: 'center', zIndex: 1000 }}>
      <div style={{ background: '#ffffff', padding: '24px', borderRadius: '8px', width: '450px', textAlign: isRtl ? 'right' : 'left' }}>
        <h3 style={{ marginTop: 0, marginBottom: '20px', color: '#2a3142' }}>{t('addTransaction')}</h3>
        <form onSubmit={handleSubmit}>
          <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: '12px', marginBottom: '12px' }}>
            <div><label style={{ display: 'block', fontSize: '14px', fontWeight: 500, marginBottom: '4px' }}>{t('date')} *</label><input required type="date" value={form.date} onChange={(e) => setForm({ ...form, date: e.target.value })} style={{ width: '100%', height: '40px', fontSize: '14px', borderRadius: '0', padding: '0 12px', border: '1px solid #ced4da', textAlign: isRtl ? 'right' : 'left' }} /></div>
            <div><label style={{ display: 'block', fontSize: '14px', fontWeight: 500, marginBottom: '4px' }}>{t('type')} *</label><select required value={form.type} onChange={(e) => setForm({ ...form, type: e.target.value as any, category: e.target.value === 'Income' ? 'Other Income' : 'Other Expense' })} style={{ width: '100%', height: '40px', fontSize: '14px', borderRadius: '0', padding: '0 12px', border: '1px solid #ced4da', textAlign: isRtl ? 'right' : 'left' }}><option value="Income">{t('income')}</option><option value="Expense">{t('expense')}</option></select></div>
          </div>
          <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: '12px', marginBottom: '12px' }}>
            <div><label style={{ display: 'block', fontSize: '14px', fontWeight: 500, marginBottom: '4px' }}>{t('category')} *</label><select required value={form.category} onChange={(e) => setForm({ ...form, category: e.target.value })} style={{ width: '100%', height: '40px', fontSize: '14px', borderRadius: '0', padding: '0 12px', border: '1px solid #ced4da', textAlign: isRtl ? 'right' : 'left' }}>{categories.map(c => <option key={c} value={c}>{getCategoryLabel(c)}</option>)}</select></div>
            <div><label style={{ display: 'block', fontSize: '14px', fontWeight: 500, marginBottom: '4px' }}>{t('amount')} *</label><input required type="number" value={form.amount} onChange={(e) => setForm({ ...form, amount: e.target.value })} style={{ width: '100%', height: '40px', fontSize: '14px', borderRadius: '0', padding: '0 12px', border: '1px solid #ced4da', textAlign: isRtl ? 'right' : 'left' }} /></div>
          </div>
          <div style={{ marginBottom: '16px' }}><label style={{ display: 'block', fontSize: '14px', fontWeight: 500, marginBottom: '4px' }}>{t('description')} *</label><input required value={form.description} onChange={(e) => setForm({ ...form, description: e.target.value })} style={{ width: '100%', height: '40px', fontSize: '14px', borderRadius: '0', padding: '0 12px', border: '1px solid #ced4da', textAlign: isRtl ? 'right' : 'left' }} /></div>
          <div style={{ display: 'flex', gap: '12px', justifyContent: 'flex-end', flexDirection: isRtl ? 'row-reverse' : 'row' }}>
            <button type="button" onClick={onClose} style={{ padding: '10px 20px', fontSize: '14px', border: '1px solid #ced4da', borderRadius: '3px', background: '#ffffff', cursor: 'pointer' }}>{commonT('cancel')}</button>
            <button type="submit" disabled={loading} style={{ padding: '10px 20px', fontSize: '14px', border: 'none', borderRadius: '3px', background: '#28aaa9', color: '#ffffff', cursor: loading ? 'not-allowed' : 'pointer', opacity: loading ? 0.6 : 1 }}>{loading ? commonT('loading') : commonT('save')}</button>
          </div>
        </form>
      </div>
    </div>
  );
}

function EditTransactionModal({ transaction, onClose, onSave }: { transaction: Transaction; onClose: () => void; onSave: (id: string, data: any) => void }) {
  const t = useTranslations('Finance');
  const commonT = useTranslations('Common');
  const locale = useLocale();
  const isRtl = locale === 'ar';

  const [form, setForm] = useState({
    date: new Date(transaction.date).toISOString().split('T')[0],
    type: transaction.type,
    category: transaction.category,
    amount: transaction.amount.toString(),
    description: transaction.description,
  });
  const [loading, setLoading] = useState(false);

  const categories = [
    'Car Purchase', 'Car Repair', 'Salary Payment', 'Office Expense', 
    'Cash Sale', 'Installment Payment', 'Rental Income', 'Other Income', 'Other Expense'
  ];

  const getCategoryLabel = (cat: string) => {
    const key = cat.replace(' ', '').charAt(0).toLowerCase() + cat.replace(' ', '').slice(1);
    return t(`categories.${key}`);
  };

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    setLoading(true);
    try {
      await onSave(transaction._id, form);
    } catch (err) { console.error(err); } finally { setLoading(false); }
  };

  return (
    <div style={{ position: 'fixed', top: 0, left: 0, right: 0, bottom: 0, background: 'rgba(0,0,0,0.5)', display: 'flex', alignItems: 'center', justifyContent: 'center', zIndex: 1000 }}>
      <div style={{ background: '#ffffff', padding: '24px', borderRadius: '8px', width: '500px', maxWidth: '90%', textAlign: isRtl ? 'right' : 'left' }}>
        <h3 style={{ marginTop: 0, marginBottom: '20px', color: '#2a3142' }}>{t('editTransaction')} - {transaction.transactionId}</h3>
        <form onSubmit={handleSubmit}>
          <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: '12px', marginBottom: '16px' }}>
            <div><label style={{ display: 'block', fontSize: '14px', fontWeight: 500, marginBottom: '4px' }}>{t('date')} *</label><input required type="date" value={form.date} onChange={(e) => setForm({ ...form, date: e.target.value })} style={{ width: '100%', height: '40px', fontSize: '14px', borderRadius: '0', padding: '0 12px', border: '1px solid #ced4da', textAlign: isRtl ? 'right' : 'left' }} /></div>
            <div><label style={{ display: 'block', fontSize: '14px', fontWeight: 500, marginBottom: '4px' }}>{t('type')} *</label><select required value={form.type} onChange={(e) => setForm({ ...form, type: e.target.value as 'Income' | 'Expense' })} style={{ width: '100%', height: '40px', fontSize: '14px', borderRadius: '0', padding: '0 12px', border: '1px solid #ced4da', textAlign: isRtl ? 'right' : 'left' }}><option value="Income">{t('income')}</option><option value="Expense">{t('expense')}</option></select></div>
            <div><label style={{ display: 'block', fontSize: '14px', fontWeight: 500, marginBottom: '4px' }}>{t('category')} *</label><select required value={form.category} onChange={(e) => setForm({ ...form, category: e.target.value })} style={{ width: '100%', height: '40px', fontSize: '14px', borderRadius: '0', padding: '0 12px', border: '1px solid #ced4da', textAlign: isRtl ? 'right' : 'left' }}>{categories.map(c => <option key={c} value={c}>{getCategoryLabel(c)}</option>)}</select></div>
            <div><label style={{ display: 'block', fontSize: '14px', fontWeight: 500, marginBottom: '4px' }}>{t('amount')} *</label><input required type="number" value={form.amount} onChange={(e) => setForm({ ...form, amount: e.target.value })} style={{ width: '100%', height: '40px', fontSize: '14px', borderRadius: '0', padding: '0 12px', border: '1px solid #ced4da', textAlign: isRtl ? 'right' : 'left' }} /></div>
          </div>
          <div style={{ marginBottom: '16px' }}><label style={{ display: 'block', fontSize: '14px', fontWeight: 500, marginBottom: '4px' }}>{t('description')} *</label><input required value={form.description} onChange={(e) => setForm({ ...form, description: e.target.value })} style={{ width: '100%', height: '40px', fontSize: '14px', borderRadius: '0', padding: '0 12px', border: '1px solid #ced4da', textAlign: isRtl ? 'right' : 'left' }} /></div>
          <div style={{ display: 'flex', gap: '12px', justifyContent: 'flex-end', marginTop: '16px', flexDirection: isRtl ? 'row-reverse' : 'row' }}>
            <button type="button" onClick={onClose} style={{ padding: '10px 20px', fontSize: '14px', border: '1px solid #ced4da', borderRadius: '3px', background: '#ffffff', cursor: 'pointer' }}>{commonT('close')}</button>
            <button type="submit" disabled={loading} style={{ padding: '10px 20px', fontSize: '14px', border: 'none', borderRadius: '3px', background: '#28aaa9', color: '#ffffff', cursor: loading ? 'not-allowed' : 'pointer', opacity: loading ? 0.6 : 1 }}>{loading ? commonT('loading') : commonT('save')}</button>
          </div>
        </form>
      </div>
    </div>
  );
}
