import { NextRequest, NextResponse } from 'next/server';
import mongoose from 'mongoose';
import { connectDB, DatabaseConnectionError } from '@/lib/db';
import SalaryPayment from '@/models/SalaryPayment';
import Employee from '@/models/Employee';
import Transaction from '@/models/Transaction';
import { getAuthPayload } from '@/lib/apiAuth';
import { logActivity } from '@/lib/activityLogger';
import { sendSalaryPaymentNotifications } from '@/lib/salaryNotifications';

export async function GET(request: NextRequest) {
  try {
    await connectDB();
    const user = await getAuthPayload(request);
    if (!user) {
      return NextResponse.json({ error: 'Unauthorized' }, { status: 401 });
    }

    if (!['Admin', 'Accountant', 'Finance Manager'].includes(user.normalizedRole || '')) {
      return NextResponse.json({ error: 'Forbidden' }, { status: 403 });
    }

    const { searchParams } = new URL(request.url);
    const page = parseInt(searchParams.get('page') || '1');
    const limit = parseInt(searchParams.get('limit') || '15');
    const employeeId = searchParams.get('employeeId') || '';
    const month = searchParams.get('month') ? parseInt(searchParams.get('month')!) : null;
    const year = searchParams.get('year') ? parseInt(searchParams.get('year')!) : null;
    const paymentType = searchParams.get('paymentType') || '';

    const query: Record<string, unknown> = {
      status: { $ne: 'Cancelled' },
    };

    if (employeeId) query.employee = employeeId;
    if (month) query.month = month;
    if (year) query.year = year;
    if (paymentType) query.paymentType = paymentType;

    const now = new Date();
    const skip = (page - 1) * limit;
    const [payments, total, totalShownAgg, monthlyTotal] = await Promise.all([
      SalaryPayment.find(query).sort({ paymentDate: -1 }).skip(skip).limit(limit).lean(),
      SalaryPayment.countDocuments(query),
      SalaryPayment.aggregate([
        { $match: query },
        { $group: { _id: null, total: { $sum: '$amount' } } },
      ]),
      SalaryPayment.aggregate([
        { $match: { month: now.getMonth() + 1, year: now.getFullYear() } },
        { $group: { _id: null, total: { $sum: '$amount' } } },
      ]),
    ]);

    return NextResponse.json({
      payments,
      pagination: { page, limit, total, pages: Math.ceil(total / limit) },
      totalThisMonth: monthlyTotal[0]?.total || 0,
      totalShown: totalShownAgg[0]?.total || 0,
    });
  } catch (error) {
    console.error('Get salary payments error:', error);
    if (error instanceof DatabaseConnectionError) {
      return NextResponse.json({ error: error.message }, { status: error.statusCode });
    }
    return NextResponse.json({ error: 'Internal server error' }, { status: 500 });
  }
}

export async function POST(request: NextRequest) {
  try {
    await connectDB();
    const user = await getAuthPayload(request);
    if (!user) {
      return NextResponse.json({ error: 'Unauthorized' }, { status: 401 });
    }

    if (!['Admin', 'Accountant', 'Finance Manager'].includes(user.normalizedRole || '')) {
      return NextResponse.json({ error: 'Forbidden' }, { status: 403 });
    }

    const body = await request.json();
    const { employee, employeeId, employeeName, amount, paymentDate, month, year, paymentType, notes } = body;

    if (!employee || !employeeId || !employeeName || !amount || !paymentDate || !month || !year) {
      return NextResponse.json({ error: 'Required fields missing' }, { status: 400 });
    }

    const session = await mongoose.startSession();
    let payment;

    try {
      await session.withTransaction(async () => {
        const payments = await SalaryPayment.create([{
          employee, employeeId, employeeName, amount, paymentDate, month, year,
          paymentType: paymentType || 'Monthly', notes,
          createdBy: user.userId,
        }], { session });

        payment = payments[0];

        // Create transaction record
        await Transaction.create([{
          date: new Date(paymentDate),
          type: 'Expense',
          category: 'Salary Payment',
          amount,
          description: `Salary payment to ${employeeName} - ${paymentType || 'Monthly'}`,
          referenceId: payment._id.toString(),
          referenceType: 'SalaryPayment',
          isAutoGenerated: true,
          createdBy: user.userId,
        }], { session });

        await logActivity({
          userId: user.userId,
          userName: user.name,
          action: `Recorded salary payment: $${amount} to ${employeeName}`,
          module: 'HR',
          targetId: payment._id.toString(),
          ipAddress: request.headers.get('x-forwarded-for') || 'unknown',
        });
      });
    } catch (txError) {
      console.error('Salary payment transaction failed:', txError);
      throw txError;
    } finally {
      await session.endSession();
    }

    if (!payment) {
      throw new Error('Failed to record salary payment');
    }

    // Send notification to employee
    try {
      const employeeData = await Employee.findById(employee).lean();
      if (employeeData) {
        await sendSalaryPaymentNotifications(
          {
            name: employeeData.name,
            phone: employeeData.phone,
            email: employeeData.email,
          },
          {
            paymentId: (payment as any).paymentId,
            employeeId: (payment as any).employeeId,
            amount: (payment as any).amount,
            paymentDate: (payment as any).paymentDate,
            month: (payment as any).month,
            year: (payment as any).year,
            paymentType: (payment as any).paymentType as 'Monthly' | 'Bonus' | 'Advance' | 'Deduction',
            notes: (payment as any).notes,
          }
        );
      }
    } catch (notifyError) {
      console.error('Employee notification failed:', notifyError);
    }

    return NextResponse.json({ payment }, { status: 201 });
  } catch (error) {
    console.error('Create salary payment error:', error);
    if (error instanceof DatabaseConnectionError) {
      return NextResponse.json({ error: error.message }, { status: error.statusCode });
    }
    return NextResponse.json({ error: 'Internal server error' }, { status: 500 });
  }
}
