import { NextRequest, NextResponse } from 'next/server';
import { connectDB, runInTransaction } from '@/lib/db';
import Rental from '@/models/Rental';
import Transaction from '@/models/Transaction';
import { getAuthPayload } from '@/lib/apiAuth';
import { logActivity } from '@/lib/activityLogger';

export async function POST(
  request: NextRequest,
  { params }: { params: Promise<{ id: string }> }
) {
  try {
    await connectDB();
    const user = await getAuthPayload(request);
    if (!user) {
      return NextResponse.json({ error: 'Unauthorized' }, { status: 401 });
    }

    const { id } = await params;
    const body = await request.json();
    const { amount, method, reference, note, date, voucherNumber } = body;

    if (!amount || amount <= 0) {
      return NextResponse.json({ error: 'Invalid amount' }, { status: 400 });
    }

    const result = await runInTransaction(async (session) => {
      const rental = await Rental.findById(id).session(session);
      if (!rental) throw new Error('Rental not found');

      const paymentAmount = Number(amount);
      rental.paidAmount = (rental.paidAmount || 0) + paymentAmount;
      rental.remainingAmount = Math.max(0, (rental.remainingAmount || 0) - paymentAmount);
      
      rental.payments.push({
        amount: paymentAmount,
        date: date ? new Date(date) : new Date(),
        method: method || 'Cash',
        reference: reference || '',
        voucherNumber: voucherNumber || '',
        note: note || 'Rental Payment',
      });

      await rental.save({ session });

      await Transaction.create([{
        date: date ? new Date(date) : new Date(),
        type: 'Income',
        category: 'Rental Income',
        amount: paymentAmount,
        description: `Rental Payment ${rental.rentalId} - ${note || ''}`,
        referenceId: rental._id.toString(),
        referenceType: 'Rental',
        isAutoGenerated: true,
        createdBy: user.userId,
      }], { session, ordered: true });

      return rental;
    });

    await logActivity({
      userId: user.userId,
      userName: user.name,
      action: `Recorded payment of SAR ${amount} for rental ${result.rentalId}`,
      module: 'Rental',
      targetId: id,
      ipAddress: request.headers.get('x-forwarded-for') || 'unknown',
    });

    return NextResponse.json({ rental: result });
  } catch (error: any) {
    console.error('Record payment error:', error);
    return NextResponse.json({ error: error.message || 'Internal server error' }, { status: 500 });
  }
}
