import mongoose from 'mongoose';
import ZatcaConfig from '../src/models/ZatcaConfig';

const prodConfig = {
  sellerName: "Amyal Plus company Ltd",
  sellerNameAr: "شركة أميال بلس المحدودة",
  trn: "312227270300003",
  address: {
    buildingNumber: "7636",
    streetName: "Muhammad Ibn Ahmad Abi Shiba",
    district: "Al Shifa Dist.",
    city: "RIYADH",
    postalCode: "14721",
    countryCode: "SA"
  },
  environment: "production",
  pih: "NWZlY2ViNjZmZmM4NmYzOGQ5NTI3ODZjNmQ2OTZjOTljMmYxN2ZiNTVkMzRlYzYzMDMzNjE5YTM0ZGY4YjEwNw==",
  isActive: true,
  privateKey: "-----BEGIN EC PRIVATE KEY-----\nMHQCAQEEIH4ko72mZpq9iqIszJW9ZbHi4Ulm2h21WwIrGZwQdH2XoAcGBSuBBAAK\noUQDQgAEHSDbaCSIf2+ncD9hsBLFPWn0hV4wS7/nBz+HLWYVRI6jqOR/NFhWUv/b\nxWr+YqLPlZIUDmzkkIr2KCEgRgxCaQ==\n-----END EC PRIVATE KEY-----",
  publicKey: "-----BEGIN PUBLIC KEY-----\nMFYwEAYHKoZIzj0CAQYFK4EEAAoDQgAExv/V4+namGrwY+YbVwynIrHhkOLe/rDR\npLYEdC1ZXJkqb3Hd5iuoxYjZDXTdm0OhsdbCNBN6gyVHRrjGB037CA==\n-----END PUBLIC KEY-----\n",
  certificate: "-----BEGIN CERTIFICATE-----\nMIIE9zCCBJ2gAwIBAgITXAACOXFgr4Fk1HT2hgABAAI5cTAKBggqhkjOPQQDAjBiMRUwEwYKCZImiZPyLGQBGRYFbG9jYWwxEzARBgoJkiaJk/IsZAEZFgNnb3YxFzAVBgoJkiaJk/IsZAEZFgdleHRnYXp0MRswGQYDVQQDExJQUlpFSU5WT0lDRVNDQTItQ0EwHhcNMjYwNDI4MTg1MzUwWhcNMzAwNDAyMDM0MTE3WjBXMQswCQYDVQQGEwJTQTEfMB0GA1UEChMWQW15YWwgUGx1cyBjb21wYW55IEx0ZDENMAsGA1UECxMETWFpbjEYMBYGA1UEAxMPMzEyMjI3MjcwMzAwMDAzMFYwEAYHKoZIzj0CAQYFK4EEAAoDQgAEHjL7G9cKszfeffvsWtp9NpIJlzdYV3GZKYLnS77HBJCKoOGUNiXNfkHU3MeAjaOW7Y2ye8R/7pfD2QAHzKHS06OCAz4wggM6MIGoBgNVHREEgaAwgZ2kgZowgZcxHDAaBgNVBAQMEzEtQW15YWx8Mi1WMXwzLTY3ODkxHzAdBgoJkiaJk/IsZAEBDA8zMTIyMjcyNzAzMDAwMDMxDTALBgNVBAwMBDExMDAxMjAwBgNVBBoMKTc2MzYgTXVoYW1tYWQgSWJuIEFobWFkIEFiaSBTaGliYSwgUklZQURIMRMwEQYDVQQPDApBdXRvbW90aXZlMB0GA1UdDgQWBBTvM06bp1R1KGLvI9qjJsPceKjbXzAfBgNVHSMEGDAWgBRZyHKeeTVp6rzZldTX4GRpAgYQGTCB5QYDVR0fBIHdMIHaMIHXoIHUoIHRhoHObGRhcDovLy9DTj1QUlpFSU5WT0lDRVNDQTItQ0EoMSksQ049UFJaRUlOVk9JQ0VTQ0EyLENOPUNEUCxDTj1QdWJsaWMlMjBLZXklMjBTZXJ2aWNlcyxDTj1TZXJ2aWNlcyxDTj1Db25maWd1cmF0aW9uLERDPWV4dHphdGNhLERDPWdvdixEQz1sb2NhbD9jZXJ0aWZpY2F0ZVJldm9jYXRpb25MaXN0P2Jhc2U/b2JqZWN0Q2xhc3M9Y1JMRGlzdHJpYnV0aW9uUG9pbnQwgc4GCCsGAQUFBwEBBIHBMIG+MIG7BggrBgEFBQcwAoaBrmxkYXA6Ly8vQ049UFJaRUlOVk9JQ0VTQ0EyLUNBLENOPUFJQSxDTj1QdWJsaWMlMjBLZXklMjBTZXJ2aWNlcyxDTj1TZXJ2aWNlcyxDTj1Db25maWd1cmF0aW9uLERDPWV4dHphdGNhLERDPWdvdixEQz1sb2NhbD9jQUNlcnRpZmljYXRlP2Jhc2U/b2JqZWN0Q2xhc3M9Y2VydGlmaWNhdGlvbkF1dGhvcml0eTAOBgNVHQ8BAf8EBAMCB4AwPAYJKwYBBAGCNxUHBC8wLQYlKwYBBAGCNxUIgYaoHYTQ+xKG7Z0kh877GdPAVWaH+qVlhdmEPgIBZAIBDjAdBgNVHSUEFjAUBggrBgEFBQcDAwYIKwYBBQUHAwIwJwYJKwYBBAGCNxUKBBowGDAKBggrBgEFBQcDAzAKBggrBgEFBQcDAjAKBggqhkjOPQQDAgNIADBFAiBUnw3vkXiI+fT1P5lEhcBM2hRNxkmUZnKkg/888GHf7gIhAMrFBwt47I4eg9GPoc5Y7nEi7UsUlnPvDvdagLSSKESO\n-----END CERTIFICATE-----",
  complianceCsid: "-----BEGIN CERTIFICATE-----\nMIICGzCCAcCgAwIBAgIGAZ3VeYqAMAoGCCqGSM49BAMCMBUxEzARBgNVBAMMCmVJbnZvaWNpbmcwHhcNMjYwNDI4MTkwMzIwWhcNMzEwNDI3MjEwMDAwWjBXMRgwFgYDVQQDDA8zMTIyMjcyNzAzMDAwMDMxDTALBgNVBAsMBE1haW4xHzAdBgNVBAoMFkFteWFsIFBsdXMgY29tcGFueSBMdGQxCzAJBgNVBAYTAlNBMFYwEAYHKoZIzj0CAQYFK4EEAAoDQgAEHjL7G9cKszfeffvsWtp9NpIJlzdYV3GZKYLnS77HBJCKoOGUNiXNfkHU3MeAjaOW7Y2ye8R/7pfD2QAHzKHS06OBvDCBuTAMBgNVHRMBAf8EAjAAMIGoBgNVHREEgaAwgZ2kgZowgZcxHDAaBgNVBAQMEzEtQW15YWx8Mi1WMXwzLTY3ODkxHzAdBgoJkiaJk/IsZAEBDA8zMTIyMjcyNzAzMDAwMDMxDTALBgNVBAwMBDExMDAxMjAwBgNVBBoMKTc2MzYgTXVoYW1tYWQgSWJuIEFobWFkIEFiaSBTaGliYSwgUklZQURIMRMwEQYDVQQPDApBdXRvbW90aXZlMAoGCCqGSM49BAMCA0kAMEYCIQDvAjY4119omFj7XhKUIaQ/Mqn6U8GjqfdIS5C0GoJunAIhAP6nay12bncmpsK5pXkYTOGkhihsGkoVvbKnYA7wXmFj\n-----END CERTIFICATE-----",
  complianceCsidSecret: "RKBFw2aRAteixgcjxPq4+Ljhvln9Q+5vmUbltWrWExs=",
  productionCsid: "-----BEGIN CERTIFICATE-----\nMIIE9zCCBJ2gAwIBAgITXAACOXFgr4Fk1HT2hgABAAI5cTAKBggqhkjOPQQDAjBiMRUwEwYKCZImiZPyLGQBGRYFbG9jYWwxEzARBgoJkiaJk/IsZAEZFgNnb3YxFzAVBgoJkiaJk/IsZAEZFgdleHRnYXp0MRswGQYDVQQDExJQUlpFSU5WT0lDRVNDQTItQ0EwHhcNMjYwNDI4MTg1MzUwWhcNMzAwNDAyMDM0MTE3WjBXMQswCQYDVQQGEwJTQTEfMB0GA1UEChMWQW15YWwgUGx1cyBjb21wYW55IEx0ZDENMAsGA1UECxMETWFpbjEYMBYGA1UEAxMPMzEyMjI3MjcwMzAwMDAzMFYwEAYHKoZIzj0CAQYFK4EEAAoDQgAEHjL7G9cKszfeffvsWtp9NpIJlzdYV3GZKYLnS77HBJCKoOGUNiXNfkHU3MeAjaOW7Y2ye8R/7pfD2QAHzKHS06OCAz4wggM6MIGoBgNVHREEgaAwgZ2kgZowgZcxHDAaBgNVBAQMEzEtQW15YWx8Mi1WMXwzLTY3ODkxHzAdBgoJkiaJk/IsZAEBDA8zMTIyMjcyNzAzMDAwMDMxDTALBgNVBAwMBDExMDAxMjAwBgNVBBoMKTc2MzYgTXVoYW1tYWQgSWJuIEFobWFkIEFiaSBTaGliYSwgUklZQURIMRMwEQYDVQQPDApBdXRvbW90aXZlMB0GA1UdDgQWBBTvM06bp1R1KGLvI9qjJsPceKjbXzAfBgNVHSMEGDAWgBRZyHKeeTVp6rzZldTX4GRpAgYQGTCB5QYDVR0fBIHdMIHaMIHXoIHUoIHRhoHObGRhcDovLy9DTj1QUlpFSU5WT0lDRVNDQTItQ0EoMSksQ049UFJaRUlOVk9JQ0VTQ0EyLENOPUNEUCxDTj1QdWJsaWMlMjBLZXklMjBTZXJ2aWNlcyxDTj1TZXJ2aWNlcyxDTj1Db25maWd1cmF0aW9uLERDPWV4dHphdGNhLERDPWdvdixEQz1sb2NhbD9jZXJ0aWZpY2F0ZVJldm9jYXRpb25MaXN0P2Jhc2U/b2JqZWN0Q2xhc3M9Y1JMRGlzdHJpYnV0aW9uUG9pbnQwgc4GCCsGAQUFBwEBBIHBMIG+MIG7BggrBgEFBQcwAoaBrmxkYXA6Ly8vQ049UFJaRUlOVk9JQ0VTQ0EyLUNBLENOPUFJQSxDTj1QdWJsaWMlMjBLZXklMjBTZXJ2aWNlcyxDTj1TZXJ2aWNlcyxDTj1Db25maWd1cmF0aW9uLERDPWV4dHphdGNhLERDPWdvdixEQz1sb2NhbD9jQUNlcnRpZmljYXRlP2Jhc2U/b2JqZWN0Q2xhc3M9Y2VydGlmaWNhdGlvbkF1dGhvcml0eTAOBgNVHQ8BAf8EBAMCB4AwPAYJKwYBBAGCNxUHBC8wLQYlKwYBBAGCNxUIgYaoHYTQ+xKG7Z0kh877GdPAVWaH+qVlhdmEPgIBZAIBDjAdBgNVHSUEFjAUBggrBgEFBQcDAwYIKwYBBQUHAwIwJwYJKwYBBAGCNxUKBBowGDAKBggrBgEFBQcDAzAKBggrBgEFBQcDAjAKBggqhkjOPQQDAgNIADBFAiBUnw3vkXiI+fT1P5lEhcBM2hRNxkmUZnKkg/888GHf7gIhAMrFBwt47I4eg9GPoc5Y7nEi7UsUlnPvDvdagLSSKESO\n-----END CERTIFICATE-----",
  productionCsidSecret: "PzmIrBQwOv6o911jqfKtl00tkZ6X7qmpYWTZiJySN8Y=",
};

async function sync() {
  const dotenv = await import('dotenv');
  dotenv.config({ path: '.env.local' });
  
  const uri = process.env.MONGODB_URI || 'mongodb://127.0.0.1:27017/car_dealership';
  await mongoose.connect(uri);
  console.log('✅ Connected to Local MongoDB');

  // Deactivate any existing configs
  await ZatcaConfig.updateMany({}, { $set: { isActive: false } });

  // Upsert the production config
  const result = await ZatcaConfig.findOneAndUpdate(
    { trn: prodConfig.trn },
    { $set: prodConfig },
    { upsert: true, new: true }
  );

  console.log('🚀 ZATCA Production Config Synced Locally:');
  console.log('ID:', result._id);
  console.log('Seller:', result.sellerName);
  console.log('Environment:', result.environment);
  
  await mongoose.disconnect();
}

sync().catch(err => {
  console.error('❌ Sync failed:', err);
  process.exit(1);
});
