import { NextRequest, NextResponse } from 'next/server';
import { connectDB, DatabaseConnectionError } from '@/lib/db';
import Rental from '@/models/Rental';
import Car from '@/models/Car';
import Customer from '@/models/Customer';
import Transaction from '@/models/Transaction';
import { getAuthPayload } from '@/lib/apiAuth';
import { logActivity } from '@/lib/activityLogger';
import { sendRentalConfirmationNotifications } from '@/lib/saleNotifications';
import { processZatcaInvoice, calculateVat, ZATCA_VAT_RATE } from '@/lib/zatca/invoiceService';
import mongoose from 'mongoose';

export async function GET(request: NextRequest) {
  try {
    await connectDB();
    const user = await getAuthPayload(request);
    if (!user) {
      return NextResponse.json({ error: 'Unauthorized' }, { status: 401 });
    }

    const { searchParams } = new URL(request.url);
    const page = parseInt(searchParams.get('page') || '1');
    const limit = parseInt(searchParams.get('limit') || '15');
    const search = searchParams.get('search') || '';
    const status = searchParams.get('status') || '';
    const customerId = searchParams.get('customer');

    const statusFilter = { status: { $nin: ['Cancelled', 'Completed'] } };

    let query: Record<string, unknown> = { ...statusFilter };

    if (customerId) {
      query.customer = new mongoose.Types.ObjectId(customerId);
    }

    if (search) {
      query = {
        $and: [
          statusFilter,
          {
            $or: [
              { customerName: { $regex: search, $options: 'i' } },
              { carId: { $regex: search, $options: 'i' } },
              { rentalId: { $regex: search, $options: 'i' } },
            ]
          }
        ]
      };
    }

    if (status) {
      query.status = status;
    }

    const skip = (page - 1) * limit;
    const [rentals, total, totalStatsAgg] = await Promise.all([
      Rental.find(query)
        .sort({ startDate: -1 })
        .skip(skip)
        .limit(limit)
        .populate('car', 'carId brand model images')
        .populate('customer', 'fullName phone profilePhoto')
        .lean(),
      Rental.countDocuments(query),
      Rental.aggregate([
        { $match: query },
        { $group: { _id: null, total: { $sum: '$totalAmount' } } },
      ]),
    ]);

    return NextResponse.json({
      rentals,
      pagination: { page, limit, total, pages: Math.ceil(total / limit) },
      totalRevenue: totalStatsAgg[0]?.total || 0,
    });
  } catch (error) {
    console.error('Get rentals error:', error);
    if (error instanceof DatabaseConnectionError) {
      return NextResponse.json({ error: error.message }, { status: error.statusCode });
    }
    return NextResponse.json({ error: 'Internal server error' }, { status: 500 });
  }
}

export async function POST(request: NextRequest) {
  try {
    await connectDB();
    const user = await getAuthPayload(request);
    if (!user) {
      return NextResponse.json({ error: 'Unauthorized' }, { status: 401 });
    }

    const body = await request.json();
    const {
      carId, car, customer, customerName, customerPhone,
      startDate, endDate, dailyRate, securityDeposit, notes,
      invoiceType, buyerTrn,
      agentName, agentCommission,
    } = body;

    if (!carId || !car || !customer || !customerName || !customerPhone || !startDate || !endDate || !dailyRate) {
      return NextResponse.json({ error: 'Required fields missing' }, { status: 400 });
    }

    const start = new Date(startDate);
    const end = new Date(endDate);
    const days = Math.ceil((end.getTime() - start.getTime()) / (1000 * 60 * 60 * 24));
    const totalAmount = days * dailyRate;
    const vatInfo = calculateVat(totalAmount, ZATCA_VAT_RATE);

    const rental = await Rental.create({
      car: car,
      carId,
      customer,
      customerName,
      customerPhone,
      startDate,
      endDate,
      dailyRate,
      totalAmount,
      securityDeposit: securityDeposit || 0,
      agentName: agentName || '',
      agentCommission: agentCommission || 0,
      status: 'Active',
      notes,
      vatRate: ZATCA_VAT_RATE,
      vatAmount: vatInfo.vatAmount,
      invoiceType: invoiceType || 'Simplified',
      createdBy: user.userId,
    });

    // Batch: update car status + create income transaction + fetch customer/car in parallel
    const [customerDoc, carDoc] = await Promise.all([
      Car.findByIdAndUpdate(car, { status: 'Rented' }),
      Transaction.create({
        date: new Date(startDate),
        type: 'Income',
        category: 'Rental Income',
        amount: totalAmount,
        description: `Rental ${rental.rentalId} - Car ${carId}`,
        referenceId: rental._id.toString(),
        referenceType: 'Rental',
        isAutoGenerated: true,
        createdBy: user.userId,
      }),
      Customer.findById(customer).lean(),
      Car.findById(car).lean(),
    ]).then(([, , cDoc, vDoc]) => [cDoc, vDoc] as const);

    // Process ZATCA invoice
    try {
      const rentalDesc = carDoc
        ? `Rental - ${carDoc.brand} ${carDoc.model} (${days} days)`.trim()
        : `Rental - ${carId} (${days} days)`;
      const zatcaResult = await processZatcaInvoice({
        referenceId: rental._id.toString(),
        referenceType: 'Rental',
        saleId: rental.rentalId,
        invoiceType: (invoiceType as 'Standard' | 'Simplified') || 'Simplified',
        issueDate: new Date(startDate),
        buyer: {
          name: customerName,
          trn: buyerTrn,
          address: customerDoc?.address,
          city: '',
        },
        lineItems: [{
          name: rentalDesc,
          quantity: days,
          unitPrice: dailyRate,
          vatRate: ZATCA_VAT_RATE,
          vatAmount: vatInfo.vatAmount,
          totalAmount: vatInfo.totalWithVat,
        }],
        subtotal: vatInfo.subtotal,
        vatTotal: vatInfo.vatAmount,
        totalWithVat: vatInfo.totalWithVat,
        notes,
        createdBy: user.userId,
      });
      await Rental.findByIdAndUpdate(rental._id, {
        zatcaUUID: zatcaResult.uuid,
        zatcaQRCode: zatcaResult.qrCode,
        zatcaHash: zatcaResult.xmlHash,
        zatcaStatus: zatcaResult.status,
        zatcaResponse: zatcaResult.zatcaResponse,
      });
    } catch (zatcaError) {
      console.error('ZATCA processing failed:', zatcaError);
    }

    await logActivity({
      userId: user.userId,
      userName: user.name,
      action: `Created rental: ${rental.rentalId} for car ${carId}`,
      module: 'Rental',
      targetId: rental._id.toString(),
      ipAddress: request.headers.get('x-forwarded-for') || 'unknown',
    });

    // Send confirmation notifications to customer
    try {
      await sendRentalConfirmationNotifications(
        {
          name: customerName,
          phone: customerPhone,
          email: customerDoc?.email,
        },
        {
          rentalId: rental.rentalId,
          carId: rental.carId,
          carBrand: carDoc?.brand,
          carModel: carDoc?.model,
          startDate: rental.startDate.toString(),
          endDate: rental.endDate.toString(),
          totalAmount: rental.totalAmount,
          dailyRate: rental.dailyRate,
          vatRate: rental.vatRate,
          vatAmount: rental.vatAmount,
          finalPriceWithVat: rental.totalAmountWithVat,
        }
      );
    } catch (notifyError) {
      console.error('Customer notification failed:', notifyError);
    }

    return NextResponse.json({ rental }, { status: 201 });
  } catch (error) {
    console.error('Create rental error:', error);
    if (error instanceof DatabaseConnectionError) {
      return NextResponse.json({ error: error.message }, { status: error.statusCode });
    }
    return NextResponse.json({ error: 'Internal server error' }, { status: 500 });
  }
}