import { NextRequest, NextResponse } from 'next/server';
import { connectDB, DatabaseConnectionError } from '@/lib/db';
import SalaryPayment from '@/models/SalaryPayment';
import Transaction from '@/models/Transaction';
import { getAuthPayload } from '@/lib/apiAuth';
import { logActivity } from '@/lib/activityLogger';
import mongoose from 'mongoose';

export async function GET(
  request: NextRequest,
  { params }: { params: Promise<{ id: string }> }
) {
  try {
    const { id } = await params;
    const user = await getAuthPayload(request);
    if (!user) {
      return NextResponse.json({ error: 'Unauthorized' }, { status: 401 });
    }

    await connectDB();

    if (!mongoose.Types.ObjectId.isValid(id)) {
      return NextResponse.json({ error: 'Invalid payment ID' }, { status: 400 });
    }

    const payment = await SalaryPayment.findById(id);

    if (!payment) {
      return NextResponse.json({ error: 'Payment not found' }, { status: 404 });
    }

    return NextResponse.json({ payment });
  } catch (error) {
    console.error('Get salary payment error:', error);
    if (error instanceof DatabaseConnectionError) {
      return NextResponse.json({ error: error.message }, { status: error.statusCode });
    }
    return NextResponse.json({ error: 'Internal server error' }, { status: 500 });
  }
}

export async function PUT(
  request: NextRequest,
  { params }: { params: Promise<{ id: string }> }
) {
  try {
    const { id } = await params;
    const user = await getAuthPayload(request);
    if (!user) {
      return NextResponse.json({ error: 'Unauthorized' }, { status: 401 });
    }

    await connectDB();

    if (!mongoose.Types.ObjectId.isValid(id)) {
      return NextResponse.json({ error: 'Invalid payment ID' }, { status: 400 });
    }

    const payment = await SalaryPayment.findById(id);

    if (!payment) {
      return NextResponse.json({ error: 'Payment not found' }, { status: 404 });
    }

    if (payment.status === 'Cancelled') {
      return NextResponse.json({ error: 'Cannot update cancelled payment' }, { status: 400 });
    }

    const body = await request.json();
    const { amount, paymentDate, paymentType, notes } = body;

    if (amount !== undefined) payment.amount = amount;
    if (paymentDate !== undefined) payment.paymentDate = new Date(paymentDate);
    if (paymentType !== undefined) payment.paymentType = paymentType;
    if (notes !== undefined) payment.notes = notes;

    await Promise.all([
      payment.save(),
      Transaction.findOneAndUpdate(
        { referenceId: payment._id.toString(), referenceType: 'SalaryPayment', isAutoGenerated: true },
        { 
          amount: payment.amount,
          description: `Salary payment to ${payment.employeeName} - ${payment.paymentType}`
        }
      ),
    ]);

    await logActivity({
      userId: user.userId,
      userName: user.name,
      action: `Updated salary payment: ${payment.paymentId}`,
      module: 'HR',
      targetId: payment._id.toString(),
      ipAddress: request.headers.get('x-forwarded-for') || 'unknown',
    });

    return NextResponse.json({ payment });
  } catch (error) {
    console.error('Update salary payment error:', error);
    if (error instanceof DatabaseConnectionError) {
      return NextResponse.json({ error: error.message }, { status: error.statusCode });
    }
    return NextResponse.json({ error: 'Internal server error' }, { status: 500 });
  }
}

export async function DELETE(
  request: NextRequest,
  { params }: { params: Promise<{ id: string }> }
) {
  try {
    const { id } = await params;
    const user = await getAuthPayload(request);
    if (!user) {
      return NextResponse.json({ error: 'Unauthorized' }, { status: 401 });
    }

    await connectDB();

    if (!mongoose.Types.ObjectId.isValid(id)) {
      return NextResponse.json({ error: 'Invalid payment ID' }, { status: 400 });
    }

    const payment = await SalaryPayment.findById(id);

    if (!payment) {
      return NextResponse.json({ error: 'Payment not found' }, { status: 404 });
    }

    if (payment.status === 'Cancelled') {
      return NextResponse.json({ error: 'Payment already cancelled' }, { status: 400 });
    }

    // Soft delete
    payment.status = 'Cancelled';
    await Promise.all([
      payment.save(),
      Transaction.findOneAndUpdate(
        { referenceId: payment._id.toString(), referenceType: 'SalaryPayment', isAutoGenerated: true },
        { isDeleted: true }
      ),
    ]);

    await logActivity({
      userId: user.userId,
      userName: user.name,
      action: `Cancelled salary payment: ${payment.paymentId}`,
      module: 'HR',
      targetId: payment._id.toString(),
      ipAddress: request.headers.get('x-forwarded-for') || 'unknown',
    });

    return NextResponse.json({ message: 'Payment cancelled successfully' });
  } catch (error) {
    console.error('Delete salary payment error:', error);
    if (error instanceof DatabaseConnectionError) {
      return NextResponse.json({ error: error.message }, { status: error.statusCode });
    }
    return NextResponse.json({ error: 'Internal server error' }, { status: 500 });
  }
}